// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

// InputDirective* are the closed-vocabulary keys plugins may write
// into `_platform.input.directives`. Source of truth:
// `actuator/src/state.rs::InputDirectives::KNOWN_KEYS`.
export const InputDirectiveLiftKeysOnDispatch = "lift_keys_on_dispatch" as const;

// Effect* are the registered effect names plugins may declare in
// `provides.effects`. Source of truth:
// `actuator/src/effects.rs::EffectDef` inventory entries.
export const EffectDisableScreenDim = "disable_screen_dim" as const;
export const EffectMuteAudioToOtherApps = "mute_audio_to_other_apps" as const;
export const EffectPauseMicrophoneIndicator = "pause_microphone_indicator" as const;
export const EffectPreventFocusSteal = "prevent_focus_steal" as const;
export const EffectSignalRecordingActive = "signal_recording_active" as const;
export const EffectSuppressHuds = "suppress_huds" as const;
export const EffectSuppressNotifications = "suppress_notifications" as const;

// KnownInputDirectives lists the full closed-vocabulary set.
export const KnownInputDirectives = [
  "lift_keys_on_dispatch",
] as const;

// KnownEffects lists the full closed-vocabulary set.
export const KnownEffects = [
  "disable_screen_dim",
  "mute_audio_to_other_apps",
  "pause_microphone_indicator",
  "prevent_focus_steal",
  "signal_recording_active",
  "suppress_huds",
  "suppress_notifications",
] as const;
