// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts
//
// BranchKit observability bus — closed log-event vocabulary.
// See notes/DESIGN_OBSERVABILITY_BUS.md for the architectural contract.

/** Log event name constants. Use instead of string literals so vocabulary drift is a type error. */
export const LogEventAudioKeybindTriggered = "audio.keybind_triggered" as const;
export const LogEventAudioSessionEnded = "audio.session_ended" as const;
export const LogEventAudioSessionStarted = "audio.session_started" as const;
export const LogEventAudioSpeechTranscript = "audio.speech_transcript" as const;
export const LogEventBridgeLifecycle = "bridge.lifecycle" as const;
export const LogEventCommandMatched = "command.matched" as const;
export const LogEventDiagnosticMessage = "diagnostic.message" as const;
export const LogEventDispatchActionDispatched = "dispatch.action_dispatched" as const;
export const LogEventDispatchActionPanicked = "dispatch.action_panicked" as const;
export const LogEventDispatchActionRouted = "dispatch.action_routed" as const;
export const LogEventDispatchActionUnhandled = "dispatch.action_unhandled" as const;
export const LogEventDispatchTiming = "dispatch.timing" as const;
export const LogEventEffectAsserted = "effect.asserted" as const;
export const LogEventEffectRetracted = "effect.retracted" as const;
export const LogEventEventBusLagged = "event_bus.lagged" as const;
export const LogEventHudClosed = "hud.closed" as const;
export const LogEventHudFragmentPushed = "hud.fragment_pushed" as const;
export const LogEventHudOpened = "hud.opened" as const;
export const LogEventKeybindFired = "keybind.fired" as const;
export const LogEventKeybindUnresolved = "keybind.unresolved" as const;
export const LogEventNativeActionStubFired = "native.action_stub_fired" as const;
export const LogEventNativeBleLifecycle = "native.ble_lifecycle" as const;
export const LogEventNativeHidLifecycle = "native.hid_lifecycle" as const;
export const LogEventNativeWindowSkipped = "native.window_skipped" as const;
export const LogEventNativeWorldPollerEvent = "native.world_poller_event" as const;
export const LogEventOperationCompleted = "operation.completed" as const;
export const LogEventPluginDegraded = "plugin.degraded" as const;
export const LogEventPluginExited = "plugin.exited" as const;
export const LogEventPluginLifecycleOp = "plugin.lifecycle_op" as const;
export const LogEventPluginLoaded = "plugin.loaded" as const;
export const LogEventPluginReady = "plugin.ready" as const;
export const LogEventPluginRecovered = "plugin.recovered" as const;
export const LogEventPluginRpcFailed = "plugin.rpc_failed" as const;
export const LogEventPluginSandboxApplied = "plugin.sandbox_applied" as const;
export const LogEventPluginSpawned = "plugin.spawned" as const;
export const LogEventPluginStderrLine = "plugin.stderr_line" as const;
export const LogEventRpcCallCompleted = "rpc.call_completed" as const;
export const LogEventRpcCallReceived = "rpc.call_received" as const;
export const LogEventSessionControlMessage = "session.control_message" as const;
export const LogEventStateRetentionSwept = "state.retention_swept" as const;
export const LogEventStateTagCleared = "state.tag_cleared" as const;
export const LogEventStateTagLifecycleClear = "state.tag_lifecycle_clear" as const;
export const LogEventStateTagSet = "state.tag_set" as const;
export const LogEventStateTtlSwept = "state.ttl_swept" as const;
export const LogEventStateWriteAttempted = "state.write_attempted" as const;
export const LogEventStateWriteDenied = "state.write_denied" as const;
export const LogEventStateWriteSucceeded = "state.write_succeeded" as const;
export const LogEventValidationError = "validation.error" as const;
export const LogEventValidationStartupPass = "validation.startup_pass" as const;
export const LogEventValidationWarning = "validation.warning" as const;
export const LogEventWatchdogWarning = "watchdog.warning" as const;

/** Metadata for one log event. */
export interface LogEventMeta {
    name: string;
    summary: string;
    since: string;
    source: string;
    severity: string;
    redaction: string;
}

/** Closed vocabulary keyed by event name. */
export const LogEventRegistry: Record<string, LogEventMeta> = {
    "audio.keybind_triggered": { name: "audio.keybind_triggered", summary: "Global keybind triggered an action via the Swift shell.", since: "0.1.0", source: "audio", severity: "info", redaction: "none" },
    "audio.session_ended": { name: "audio.session_ended", summary: "A speech session ended (hold-to-talk released or continuous mode terminated).", since: "0.1.0", source: "audio", severity: "info", redaction: "none" },
    "audio.session_started": { name: "audio.session_started", summary: "A speech session began (hold-to-talk pressed or continuous mode entered).", since: "0.1.0", source: "audio", severity: "info", redaction: "none" },
    "audio.speech_transcript": { name: "audio.speech_transcript", summary: "Final or interim speech recognition transcript for a session.", since: "0.1.0", source: "audio", severity: "info", redaction: "full" },
    "bridge.lifecycle": { name: "bridge.lifecycle", summary: "FFI bridge lifecycle event (init, shutdown, UI server bind, callback registration).", since: "0.1.0", source: "lifecycle", severity: "info", redaction: "none" },
    "command.matched": { name: "command.matched", summary: "Speech recognition produced a match against a registered command.", since: "0.1.0", source: "dispatch", severity: "info", redaction: "none" },
    "diagnostic.message": { name: "diagnostic.message", summary: "Catch-all for ad-hoc operational text that doesn't fit a typed variant.", since: "0.1.0", source: "generic", severity: "debug", redaction: "none" },
    "dispatch.action_dispatched": { name: "dispatch.action_dispatched", summary: "An action entered the dispatch pipeline.", since: "0.1.0", source: "dispatch", severity: "debug", redaction: "none" },
    "dispatch.action_panicked": { name: "dispatch.action_panicked", summary: "A dispatch handler panicked. Process likely degraded; investigate.", since: "0.1.0", source: "dispatch", severity: "error", redaction: "none" },
    "dispatch.action_routed": { name: "dispatch.action_routed", summary: "Dispatch resolved an action to a target plugin or builtin handler.", since: "0.1.0", source: "dispatch", severity: "debug", redaction: "none" },
    "dispatch.action_unhandled": { name: "dispatch.action_unhandled", summary: "An action reached dispatch but no handler claimed it.", since: "0.1.0", source: "dispatch", severity: "warn", redaction: "none" },
    "dispatch.timing": { name: "dispatch.timing", summary: "Timing marker for dispatch / ingest / keybind operations.", since: "0.1.0", source: "dispatch", severity: "debug", redaction: "none" },
    "effect.asserted": { name: "effect.asserted", summary: "A plugin asserted ownership of an exclusive effect (granted / already-held / displaced).", since: "0.1.0", source: "effects", severity: "info", redaction: "none" },
    "effect.retracted": { name: "effect.retracted", summary: "A plugin retracted an effect assertion; ownership may transfer to a queued asserter.", since: "0.1.0", source: "effects", severity: "info", redaction: "none" },
    "event_bus.lagged": { name: "event_bus.lagged", summary: "An event-bus subscriber fell behind and dropped events.", since: "0.1.0", source: "lifecycle", severity: "warn", redaction: "none" },
    "hud.closed": { name: "hud.closed", summary: "A HUD channel was hidden.", since: "0.1.0", source: "hud", severity: "info", redaction: "none" },
    "hud.fragment_pushed": { name: "hud.fragment_pushed", summary: "Fragments were pushed to a HUD channel (high-volume; debug-level).", since: "0.1.0", source: "hud", severity: "debug", redaction: "none" },
    "hud.opened": { name: "hud.opened", summary: "A HUD channel became visible.", since: "0.1.0", source: "hud", severity: "info", redaction: "none" },
    "keybind.fired": { name: "keybind.fired", summary: "A global keybind resolved to an action.", since: "0.1.0", source: "dispatch", severity: "info", redaction: "none" },
    "keybind.unresolved": { name: "keybind.unresolved", summary: "A keybind was pressed but no binding existed.", since: "0.1.0", source: "dispatch", severity: "debug", redaction: "none" },
    "native.action_stub_fired": { name: "native.action_stub_fired", summary: "The stub native backend received an action (debug-only; not wired in production).", since: "0.1.0", source: "native", severity: "debug", redaction: "none" },
    "native.ble_lifecycle": { name: "native.ble_lifecycle", summary: "Bluetooth lifecycle event (manager init, power state, connect / discover / write errors).", since: "0.1.0", source: "native", severity: "info", redaction: "none" },
    "native.hid_lifecycle": { name: "native.hid_lifecycle", summary: "Non-Apple HID device lifecycle event (connect, disconnect, seize, release, monitor start).", since: "0.1.0", source: "native", severity: "info", redaction: "none" },
    "native.window_skipped": { name: "native.window_skipped", summary: "World poller skipped a non-standard window (debug-level).", since: "0.1.0", source: "native", severity: "debug", redaction: "none" },
    "native.world_poller_event": { name: "native.world_poller_event", summary: "World poller lifecycle event (started, seeded, batch processed, idle).", since: "0.1.0", source: "native", severity: "debug", redaction: "none" },
    "operation.completed": { name: "operation.completed", summary: "An operation handler completed execution.", since: "0.1.0", source: "dispatch", severity: "debug", redaction: "none" },
    "plugin.degraded": { name: "plugin.degraded", summary: "A managed plugin's RPC channel hit the consecutive-timeout threshold and was marked degraded.", since: "0.1.0", source: "plugins", severity: "warn", redaction: "none" },
    "plugin.exited": { name: "plugin.exited", summary: "A managed plugin process exited (clean or crashed).", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.lifecycle_op": { name: "plugin.lifecycle_op", summary: "A plugin lifecycle operation (install, uninstall, update, reload, hot-reload, enable, disable).", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.loaded": { name: "plugin.loaded", summary: "A plugin manifest was discovered and parsed.", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.ready": { name: "plugin.ready", summary: "A managed plugin completed its RPC handshake.", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.recovered": { name: "plugin.recovered", summary: "A previously-degraded plugin recovered and is responding again.", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.rpc_failed": { name: "plugin.rpc_failed", summary: "A plugin RPC method returned an error or failed to respond.", since: "0.1.0", source: "plugins", severity: "warn", redaction: "none" },
    "plugin.sandbox_applied": { name: "plugin.sandbox_applied", summary: "Sandbox profile applied (or skipped) for a managed plugin spawn.", since: "0.1.0", source: "plugins", severity: "debug", redaction: "none" },
    "plugin.spawned": { name: "plugin.spawned", summary: "A managed plugin process was spawned.", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "plugin.stderr_line": { name: "plugin.stderr_line", summary: "A managed plugin emitted a stdout/stderr line.", since: "0.1.0", source: "plugins", severity: "info", redaction: "none" },
    "rpc.call_completed": { name: "rpc.call_completed", summary: "A plugin-to-actuator RPC call completed.", since: "0.1.0", source: "plugins", severity: "debug", redaction: "none" },
    "rpc.call_received": { name: "rpc.call_received", summary: "A plugin-to-actuator RPC call was received.", since: "0.1.0", source: "plugins", severity: "debug", redaction: "none" },
    "session.control_message": { name: "session.control_message", summary: "A control message was forwarded to the Swift host (HUD show, mode reset, etc.).", since: "0.1.0", source: "dispatch", severity: "info", redaction: "none" },
    "state.retention_swept": { name: "state.retention_swept", summary: "Retention sweep removed expired records from a collection.", since: "0.1.0", source: "state", severity: "info", redaction: "none" },
    "state.tag_cleared": { name: "state.tag_cleared", summary: "One or more tags were cleared via a gate-shape collection mutation.", since: "0.1.0", source: "state", severity: "info", redaction: "none" },
    "state.tag_lifecycle_clear": { name: "state.tag_lifecycle_clear", summary: "Lifecycle policy cleared transient tags after a triggering event.", since: "0.1.0", source: "state", severity: "debug", redaction: "none" },
    "state.tag_set": { name: "state.tag_set", summary: "One or more tags were set via a gate-shape collection mutation.", since: "0.1.0", source: "state", severity: "info", redaction: "none" },
    "state.ttl_swept": { name: "state.ttl_swept", summary: "TTL sweep removed expired records from a collection.", since: "0.1.0", source: "state", severity: "debug", redaction: "none" },
    "state.write_attempted": { name: "state.write_attempted", summary: "A write to a state collection was initiated.", since: "0.1.0", source: "state", severity: "debug", redaction: "payload_hash" },
    "state.write_denied": { name: "state.write_denied", summary: "A write was rejected by auth, grants, validation, or policy.", since: "0.1.0", source: "state", severity: "warn", redaction: "none" },
    "state.write_succeeded": { name: "state.write_succeeded", summary: "A write to a state collection completed.", since: "0.1.0", source: "state", severity: "info", redaction: "none" },
    "validation.error": { name: "validation.error", summary: "Manifest validation error — plugin was rejected or not reloaded.", since: "0.1.0", source: "validation", severity: "error", redaction: "none" },
    "validation.startup_pass": { name: "validation.startup_pass", summary: "Startup validation pass completed; warning_count summarizes any drift detected.", since: "0.1.0", source: "validation", severity: "info", redaction: "none" },
    "validation.warning": { name: "validation.warning", summary: "Manifest / commands / action validation produced a warning.", since: "0.1.0", source: "validation", severity: "warn", redaction: "none" },
    "watchdog.warning": { name: "watchdog.warning", summary: "Watchdog observed mutex contention or suspected a deadlock.", since: "0.1.0", source: "lifecycle", severity: "warn", redaction: "none" },
};
