// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

import { Plugin } from "./plugin.js";
import type { AXElementNode, AXElementRef, ActionsListResponse, ActiveSpace, AudioDevice, BleService, BleWriteEntry, BluetoothDevice, ClipboardContents, ClipboardWriteItem, CollectionDeleteLogEntryResponse, CollectionGetLogEntryResponse, CollectionGetRecordingResponse, CollectionGetResponse, CollectionListLogResponse, CollectionsListSection, CommandsDiscoverResponse, CommandsHasPartialResponse, CommandsListResponse, CommandsMatchResponse, CommandsPushResponse, DeliveredNotification, DispatchResponse, DisplayMetadata, HUDRemoveChannelResponse, HidDeviceEntry, HidElementEntry, InputClipboardReadResponse, InputSource, InstalledApp, KeyNamesSetResponse, KeybindsRegisterResponse, LogEntry, LogListOpts, LoginItem, MatchAliasesGetResponse, MatchAliasesSetResponse, MenuItem, NativeAppIconResponse, NativeAxElementAtPointResponse, NativeAxObserveResponse, NativeBatteryResponse, NativeBleSubscribeAllThenWriteResponse, NativeBleSubscribeResponse, NativeBleWriteResponse, NativeBrightnessResponse, NativeCaptureWindowResponse, NativeClipboardChangeCountResponse, NativeColorAtPointResponse, NativeCurrentUserResponse, NativeCursorInfoResponse, NativeCursorResponse, NativeDarkModeResponse, NativeDefaultBrowserResponse, NativeDndResponse, NativeFrontmostAppResponse, NativeGetWindowInfoResponse, NativeHidClaimResponse, NativeHidReleaseResponse, NativeHidSendReportResponse, NativeKeyboardLayoutResponse, NativeNotifyResponse, NativeObserveWindowsResponse, NativePreventSleepResponse, NativeQuickLookResponse, NativeRunApplescriptResponse, NativeScreenshotResponse, NativeSystemUptimeResponse, NativeVolumeResponse, NativeWifiResponse, RunningApp, SelectionPickResponse, SessionEndCleanupResponse, SpaceInfo, SpotlightResult, TileableEntry, WindowFrame, WorldModel } from "./types_gen.js";
import {
  MethodActionsList,
  MethodCollectionAppend,
  MethodCollectionDelete,
  MethodCollectionDeleteLogEntry,
  MethodCollectionGet,
  MethodCollectionGetLogEntry,
  MethodCollectionGetRecording,
  MethodCollectionListLog,
  MethodCollectionOverride,
  MethodCollectionPush,
  MethodCollectionSetRecording,
  MethodCollectionsList,
  MethodCommandsDiscover,
  MethodCommandsHasPartial,
  MethodCommandsList,
  MethodCommandsMatch,
  MethodCommandsPush,
  MethodControlSignal,
  MethodDispatch,
  MethodEventsAppend,
  MethodEventsEmit,
  MethodHudCreateChannel,
  MethodHudHide,
  MethodHudPush,
  MethodHudRemoveChannel,
  MethodHudSetSize,
  MethodHudShow,
  MethodInputClick,
  MethodInputClipboardAction,
  MethodInputClipboardRead,
  MethodInputClipboardReadAll,
  MethodInputClipboardWrite,
  MethodInputClipboardWriteItems,
  MethodInputDoubleClick,
  MethodInputDrag,
  MethodInputListInputSources,
  MethodInputMouseButton,
  MethodInputPressKey,
  MethodInputRawKey,
  MethodInputRightClick,
  MethodInputScroll,
  MethodInputSwitchInputSource,
  MethodInputTypeText,
  MethodKeyNamesSet,
  MethodKeybindsRegister,
  MethodMatchAliasesGet,
  MethodMatchAliasesSet,
  MethodNativeActivateApp,
  MethodNativeActiveSpace,
  MethodNativeAppIcon,
  MethodNativeAudioDevices,
  MethodNativeAxElementAtPoint,
  MethodNativeAxElementTree,
  MethodNativeAxObserve,
  MethodNativeAxPerformAction,
  MethodNativeAxReadAttributes,
  MethodNativeAxSetAttribute,
  MethodNativeAxUnobserve,
  MethodNativeBatchIsTileable,
  MethodNativeBatchSetFrames,
  MethodNativeBattery,
  MethodNativeBleDiscoverServices,
  MethodNativeBleSubscribe,
  MethodNativeBleSubscribeAllThenWrite,
  MethodNativeBleWrite,
  MethodNativeBluetoothDevices,
  MethodNativeBorders,
  MethodNativeBrightness,
  MethodNativeCaptureWindow,
  MethodNativeClickMenuItem,
  MethodNativeClipboardChangeCount,
  MethodNativeCloseWindow,
  MethodNativeColorAtPoint,
  MethodNativeCurrentUser,
  MethodNativeCursor,
  MethodNativeCursorInfo,
  MethodNativeDarkMode,
  MethodNativeDefaultBrowser,
  MethodNativeDismissNotification,
  MethodNativeDisplays,
  MethodNativeDnd,
  MethodNativeFileTags,
  MethodNativeForceQuitApp,
  MethodNativeFrontmostApp,
  MethodNativeGetWindowInfo,
  MethodNativeHidClaim,
  MethodNativeHidDevices,
  MethodNativeHidElements,
  MethodNativeHidRelease,
  MethodNativeHidSendReport,
  MethodNativeHideApp,
  MethodNativeInstalledApps,
  MethodNativeIsAppHidden,
  MethodNativeKeyboardLayout,
  MethodNativeLaunchApp,
  MethodNativeListNotifications,
  MethodNativeListSpaces,
  MethodNativeLoginItems,
  MethodNativeMenuBar,
  MethodNativeMinimizeWindow,
  MethodNativeMoveWindowToDisplay,
  MethodNativeMoveWindowToSpace,
  MethodNativeMute,
  MethodNativeNotify,
  MethodNativeObserveWindows,
  MethodNativeOpenTarget,
  MethodNativePlaySound,
  MethodNativePollBurst,
  MethodNativePreventSleep,
  MethodNativeQuickLook,
  MethodNativeQuitApp,
  MethodNativeRaiseWindow,
  MethodNativeRevealInFinder,
  MethodNativeRunApplescript,
  MethodNativeRunningApps,
  MethodNativeScreenLock,
  MethodNativeScreenshot,
  MethodNativeSelectedFinderItems,
  MethodNativeSetAudioDevice,
  MethodNativeSetBrightness,
  MethodNativeSetDarkMode,
  MethodNativeSetDnd,
  MethodNativeSetVolume,
  MethodNativeSetWindowAlpha,
  MethodNativeSetWindowLevel,
  MethodNativeSpeak,
  MethodNativeSpotlight,
  MethodNativeSystemUptime,
  MethodNativeToggleFullscreen,
  MethodNativeTrash,
  MethodNativeUnhideApp,
  MethodNativeUnminimizeWindow,
  MethodNativeUnobserveWindows,
  MethodNativeVolume,
  MethodNativeWarpCursor,
  MethodNativeWifi,
  MethodNativeWorldModel,
  MethodSelectionPick,
  MethodSelectionSet,
  MethodSessionEndCleanup,
  MethodSettingsPatchSignals,
  MethodSettingsRefresh,
  MethodSettingsRulesCreate,
  MethodSettingsRulesUpdate,
  MethodSystemLaunchApp,
  MethodSystemNotify,
  MethodSystemRunShell,
  MethodTagsGet,
  MethodTagsModify,
} from "./contracts_gen.js";

declare module "./plugin.js" {
  interface Plugin {
    actionsList(): Promise<ActionsListResponse>;
    collectionAppend(name: string, payload: unknown): Promise<LogEntry | undefined>;
    collectionDelete(name: string): Promise<void>;
    collectionDeleteLogEntry(id: string, name: string): Promise<CollectionDeleteLogEntryResponse>;
    collectionGet(name: string): Promise<CollectionGetResponse>;
    collectionGetLogEntry(id: string, name: string): Promise<CollectionGetLogEntryResponse>;
    collectionGetRecording(name: string): Promise<CollectionGetRecordingResponse>;
    collectionListLog(name: string, opts?: LogListOpts): Promise<CollectionListLogResponse>;
    collectionOverride(action: string, collection: string, fields?: unknown, id?: unknown): Promise<void>;
    collectionPush(data: unknown, name: string, label?: unknown): Promise<void>;
    collectionSetRecording(enabled: boolean, name: string): Promise<void>;
    collectionsList(kind?: unknown): Promise<CollectionsListSection[]>;
    commandsDiscover(activeTags?: unknown, requireTag?: unknown, words?: unknown): Promise<CommandsDiscoverResponse>;
    commandsHasPartial(activeTags?: unknown, words?: string[]): Promise<CommandsHasPartialResponse>;
    commandsList(): Promise<CommandsListResponse>;
    commandsMatch(activeTags?: unknown, words?: string[]): Promise<CommandsMatchResponse>;
    commandsPush(commands?: unknown): Promise<CommandsPushResponse>;
    controlSignal(signal: string): Promise<void>;
    dispatch(action: unknown): Promise<DispatchResponse>;
    eventsAppend(eventType: string, data?: unknown, sessionId?: string): Promise<void>;
    eventsEmit(eventType: string, correlationId?: unknown, data?: unknown): Promise<void>;
    hudCreateChannel(channel: string, acceptsInput?: boolean, anchor?: unknown, description?: string, followsFocus?: boolean, minHeight?: number, width?: number): Promise<void>;
    hudHide(channel: string): Promise<void>;
    hudPush(channel: string, fragments: unknown): Promise<void>;
    hudRemoveChannel(channel: string): Promise<HUDRemoveChannelResponse>;
    hudSetSize(channel: string, height: number): Promise<void>;
    hudShow(channel: string): Promise<void>;
    inputClick(button?: string): Promise<void>;
    inputClipboardAction(action: string, text?: unknown): Promise<void>;
    inputClipboardRead(contentType: string): Promise<InputClipboardReadResponse>;
    inputClipboardReadAll(): Promise<ClipboardContents[]>;
    inputClipboardWrite(contentType: string, data: string): Promise<void>;
    inputClipboardWriteItems(items?: ClipboardWriteItem[]): Promise<void>;
    inputDoubleClick(x?: unknown, y?: unknown): Promise<void>;
    inputDrag(fromX: number, fromY: number, toX: number, toY: number, durationMs?: number): Promise<void>;
    inputListInputSources(): Promise<InputSource[]>;
    inputMouseButton(direction: string, button?: string): Promise<void>;
    inputPressKey(code?: unknown, modifiers?: string[], name?: unknown): Promise<void>;
    inputRawKey(code: number, direction: string): Promise<void>;
    inputRightClick(x?: unknown, y?: unknown): Promise<void>;
    inputScroll(direction: string, amount?: number, unit?: string): Promise<void>;
    inputSwitchInputSource(sourceId: string): Promise<boolean>;
    inputTypeText(text: string): Promise<void>;
    keyNamesSet(names?: Record<string, number>): Promise<KeyNamesSetResponse>;
    keybindsRegister(snapshot: unknown): Promise<KeybindsRegisterResponse>;
    matchAliasesGet(): Promise<MatchAliasesGetResponse>;
    matchAliasesSet(aliases?: Record<string, string>): Promise<MatchAliasesSetResponse>;
    nativeActivateApp(bundleId: string, allWindows?: boolean): Promise<void>;
    nativeActiveSpace(): Promise<ActiveSpace[]>;
    nativeAppIcon(bundleId: string, size?: number): Promise<NativeAppIconResponse>;
    nativeAudioDevices(): Promise<AudioDevice[]>;
    nativeAxElementAtPoint(pid: number, x: number, y: number): Promise<NativeAxElementAtPointResponse>;
    nativeAxElementTree(element: AXElementRef, depth?: number): Promise<AXElementNode>;
    nativeAxObserve(pid: number, notifications?: string[]): Promise<NativeAxObserveResponse>;
    nativeAxPerformAction(action: string, element: AXElementRef): Promise<boolean>;
    nativeAxReadAttributes(element: AXElementRef, attributes?: string[]): Promise<void>;
    nativeAxSetAttribute(attribute: string, element: AXElementRef, value: unknown): Promise<boolean>;
    nativeAxUnobserve(subscriptionId: string): Promise<boolean>;
    nativeBatchIsTileable(windowIds?: string[]): Promise<TileableEntry[]>;
    nativeBatchSetFrames(frames?: WindowFrame[], readback?: boolean): Promise<WindowFrame[]>;
    nativeBattery(): Promise<NativeBatteryResponse>;
    nativeBleDiscoverServices(deviceIdentifier: string): Promise<BleService[]>;
    nativeBleSubscribe(characteristicUuid: string, deviceIdentifier: string, serviceUuid: string): Promise<NativeBleSubscribeResponse>;
    nativeBleSubscribeAllThenWrite(deviceIdentifier: string, subscribeServices?: string[], writes?: BleWriteEntry[]): Promise<NativeBleSubscribeAllThenWriteResponse>;
    nativeBleWrite(characteristicUuid: string, deviceIdentifier: string, serviceUuid: string, data?: number[], writeType?: string): Promise<NativeBleWriteResponse>;
    nativeBluetoothDevices(): Promise<BluetoothDevice[]>;
    nativeBorders(): Promise<void>;
    nativeBrightness(displayId?: unknown): Promise<NativeBrightnessResponse>;
    nativeCaptureWindow(windowId: string): Promise<NativeCaptureWindowResponse>;
    nativeClickMenuItem(pid: number, path?: string[]): Promise<boolean>;
    nativeClipboardChangeCount(): Promise<NativeClipboardChangeCountResponse>;
    nativeCloseWindow(windowId: string): Promise<void>;
    nativeColorAtPoint(x: number, y: number): Promise<NativeColorAtPointResponse>;
    nativeCurrentUser(): Promise<NativeCurrentUserResponse>;
    nativeCursor(): Promise<NativeCursorResponse>;
    nativeCursorInfo(): Promise<NativeCursorInfoResponse>;
    nativeDarkMode(): Promise<NativeDarkModeResponse>;
    nativeDefaultBrowser(): Promise<NativeDefaultBrowserResponse>;
    nativeDismissNotification(id: string): Promise<void>;
    nativeDisplays(): Promise<DisplayMetadata[]>;
    nativeDnd(): Promise<NativeDndResponse>;
    nativeFileTags(path: string, tags?: unknown): Promise<void>;
    nativeForceQuitApp(bundleId: string): Promise<boolean>;
    nativeFrontmostApp(): Promise<NativeFrontmostAppResponse>;
    nativeGetWindowInfo(windowId: string): Promise<NativeGetWindowInfoResponse>;
    nativeHidClaim(deviceId: string): Promise<NativeHidClaimResponse>;
    nativeHidDevices(): Promise<HidDeviceEntry[]>;
    nativeHidElements(deviceId: string): Promise<HidElementEntry[]>;
    nativeHidRelease(deviceId: string): Promise<NativeHidReleaseResponse>;
    nativeHidSendReport(deviceId: string, reportId: number, reportType: string, data?: number[]): Promise<NativeHidSendReportResponse>;
    nativeHideApp(bundleId: string): Promise<void>;
    nativeInstalledApps(): Promise<InstalledApp[]>;
    nativeIsAppHidden(bundleId: string): Promise<boolean>;
    nativeKeyboardLayout(): Promise<NativeKeyboardLayoutResponse>;
    nativeLaunchApp(bundleId: string, newInstance?: boolean): Promise<void>;
    nativeListNotifications(): Promise<DeliveredNotification[]>;
    nativeListSpaces(): Promise<SpaceInfo[]>;
    nativeLoginItems(): Promise<LoginItem[]>;
    nativeMenuBar(pid: number): Promise<MenuItem[]>;
    nativeMinimizeWindow(windowId: string): Promise<void>;
    nativeMoveWindowToDisplay(displayId: number, windowId: string): Promise<void>;
    nativeMoveWindowToSpace(spaceId: number, windowId: string): Promise<boolean>;
    nativeMute(muted: boolean): Promise<void>;
    nativeNotify(title: string, body?: unknown, sound?: unknown, subtitle?: unknown): Promise<NativeNotifyResponse>;
    nativeObserveWindows(pid: number): Promise<NativeObserveWindowsResponse>;
    nativeOpenTarget(target: string): Promise<void>;
    nativePlaySound(name: string): Promise<void>;
    nativePollBurst(): Promise<void>;
    nativePreventSleep(assertionId?: unknown, reason?: string): Promise<NativePreventSleepResponse>;
    nativeQuickLook(path: string, size?: number): Promise<NativeQuickLookResponse>;
    nativeQuitApp(bundleId: string): Promise<boolean>;
    nativeRaiseWindow(windowId: string): Promise<void>;
    nativeRevealInFinder(path: string): Promise<void>;
    nativeRunApplescript(script: string): Promise<NativeRunApplescriptResponse>;
    nativeRunningApps(): Promise<RunningApp[]>;
    nativeScreenLock(): Promise<void>;
    nativeScreenshot(displayId?: unknown, region?: unknown, windowId?: unknown): Promise<NativeScreenshotResponse>;
    nativeSelectedFinderItems(): Promise<string[]>;
    nativeSetAudioDevice(deviceType: string, uid: string): Promise<void>;
    nativeSetBrightness(brightness: number, displayId?: unknown): Promise<void>;
    nativeSetDarkMode(dark: boolean): Promise<void>;
    nativeSetDnd(enabled: boolean): Promise<void>;
    nativeSetVolume(volume: number): Promise<void>;
    nativeSetWindowAlpha(alpha: number, windowId: string): Promise<void>;
    nativeSetWindowLevel(level: string, windowId: string): Promise<boolean>;
    nativeSpeak(text: string, rate?: unknown, voice?: unknown): Promise<void>;
    nativeSpotlight(query: string, limit?: number, scope?: unknown): Promise<SpotlightResult[]>;
    nativeSystemUptime(): Promise<NativeSystemUptimeResponse>;
    nativeToggleFullscreen(windowId: string): Promise<void>;
    nativeTrash(path: string): Promise<boolean>;
    nativeUnhideApp(bundleId: string): Promise<void>;
    nativeUnminimizeWindow(windowId: string): Promise<void>;
    nativeUnobserveWindows(subscriptionId: string): Promise<boolean>;
    nativeVolume(): Promise<NativeVolumeResponse>;
    nativeWarpCursor(x: number, y: number): Promise<void>;
    nativeWifi(): Promise<NativeWifiResponse>;
    nativeWorldModel(onScreen?: boolean): Promise<WorldModel>;
    selectionPick(index: number): Promise<SelectionPickResponse>;
    selectionSet(channel?: unknown, items?: unknown, title?: unknown): Promise<void>;
    sessionEndCleanup(): Promise<SessionEndCleanupResponse>;
    settingsPatchSignals(signals: string): Promise<void>;
    settingsRefresh(): Promise<void>;
    settingsRulesCreate(newruleactionjson?: unknown, newruleactiontype?: unknown, newruleactionval?: unknown, newrulecategory?: unknown, newruleclearstags?: unknown, newruledescription?: unknown, newrulephrase?: unknown, newrulerequirestags?: unknown, newrulesetstags?: unknown): Promise<void>;
    settingsRulesUpdate(canonical: string, newruleactionjson?: unknown, newruleactiontype?: unknown, newruleactionval?: unknown, newrulecategory?: unknown, newruleclearstags?: unknown, newruledescription?: unknown, newrulephrase?: unknown, newrulerequirestags?: unknown, newrulesetstags?: unknown): Promise<void>;
    systemLaunchApp(bundleId: string, newInstance?: boolean): Promise<void>;
    systemNotify(body: string, title: string, durationSecs?: unknown): Promise<void>;
    systemRunShell(command: string): Promise<void>;
    tagsGet(): Promise<string[]>;
    tagsModify(clear?: string[], clearScoped?: boolean, set?: string[]): Promise<string[]>;
  }
}

Plugin.prototype.actionsList = async function() {
  const result = await this.call(MethodActionsList);
  return result as ActionsListResponse;
};

Plugin.prototype.collectionAppend = async function(name: string, payload: unknown) {
  const result = await this.call(
    MethodCollectionAppend,
    {
      name,
      payload,
    },
  );
  return (result as any).entry;
};

Plugin.prototype.collectionDelete = async function(name: string) {
  const result = await this.call(
    MethodCollectionDelete,
    {
      name,
    },
  );
};

Plugin.prototype.collectionDeleteLogEntry = async function(id: string, name: string) {
  const result = await this.call(
    MethodCollectionDeleteLogEntry,
    {
      id,
      name,
    },
  );
  return result as CollectionDeleteLogEntryResponse;
};

Plugin.prototype.collectionGet = async function(name: string) {
  const result = await this.call(
    MethodCollectionGet,
    {
      name,
    },
  );
  return result as CollectionGetResponse;
};

Plugin.prototype.collectionGetLogEntry = async function(id: string, name: string) {
  const result = await this.call(
    MethodCollectionGetLogEntry,
    {
      id,
      name,
    },
  );
  return result as CollectionGetLogEntryResponse;
};

Plugin.prototype.collectionGetRecording = async function(name: string) {
  const result = await this.call(
    MethodCollectionGetRecording,
    {
      name,
    },
  );
  return result as CollectionGetRecordingResponse;
};

Plugin.prototype.collectionListLog = async function(name: string, opts?: LogListOpts) {
  const result = await this.call(
    MethodCollectionListLog,
    {
      name,
      opts,
    },
  );
  return result as CollectionListLogResponse;
};

Plugin.prototype.collectionOverride = async function(action: string, collection: string, fields?: unknown, id?: unknown) {
  const result = await this.call(
    MethodCollectionOverride,
    {
      action,
      collection,
      fields,
      id,
    },
  );
};

Plugin.prototype.collectionPush = async function(data: unknown, name: string, label?: unknown) {
  const result = await this.call(
    MethodCollectionPush,
    {
      data,
      name,
      label,
    },
  );
};

Plugin.prototype.collectionSetRecording = async function(enabled: boolean, name: string) {
  const result = await this.call(
    MethodCollectionSetRecording,
    {
      enabled,
      name,
    },
  );
};

Plugin.prototype.collectionsList = async function(kind?: unknown) {
  const result = await this.call(
    MethodCollectionsList,
    {
      kind,
    },
  );
  return (result as any).sections;
};

Plugin.prototype.commandsDiscover = async function(activeTags?: unknown, requireTag?: unknown, words?: unknown) {
  const result = await this.call(
    MethodCommandsDiscover,
    {
      active_tags: activeTags,
      require_tag: requireTag,
      words,
    },
  );
  return result as CommandsDiscoverResponse;
};

Plugin.prototype.commandsHasPartial = async function(activeTags?: unknown, words?: string[]) {
  const result = await this.call(
    MethodCommandsHasPartial,
    {
      active_tags: activeTags,
      words,
    },
  );
  return result as CommandsHasPartialResponse;
};

Plugin.prototype.commandsList = async function() {
  const result = await this.call(MethodCommandsList);
  return result as CommandsListResponse;
};

Plugin.prototype.commandsMatch = async function(activeTags?: unknown, words?: string[]) {
  const result = await this.call(
    MethodCommandsMatch,
    {
      active_tags: activeTags,
      words,
    },
  );
  return result as CommandsMatchResponse;
};

Plugin.prototype.commandsPush = async function(commands?: unknown) {
  const result = await this.call(
    MethodCommandsPush,
    {
      commands,
    },
  );
  return result as CommandsPushResponse;
};

Plugin.prototype.controlSignal = async function(signal: string) {
  const result = await this.call(
    MethodControlSignal,
    {
      signal,
    },
  );
};

Plugin.prototype.dispatch = async function(action: unknown) {
  const result = await this.call(
    MethodDispatch,
    {
      action,
    },
  );
  return result as DispatchResponse;
};

Plugin.prototype.eventsAppend = async function(eventType: string, data?: unknown, sessionId?: string) {
  const result = await this.call(
    MethodEventsAppend,
    {
      event_type: eventType,
      data,
      session_id: sessionId,
    },
  );
};

Plugin.prototype.eventsEmit = async function(eventType: string, correlationId?: unknown, data?: unknown) {
  const result = await this.call(
    MethodEventsEmit,
    {
      event_type: eventType,
      correlation_id: correlationId,
      data,
    },
  );
};

Plugin.prototype.hudCreateChannel = async function(channel: string, acceptsInput?: boolean, anchor?: unknown, description?: string, followsFocus?: boolean, minHeight?: number, width?: number) {
  const result = await this.call(
    MethodHudCreateChannel,
    {
      channel,
      accepts_input: acceptsInput,
      anchor,
      description,
      follows_focus: followsFocus,
      min_height: minHeight,
      width,
    },
  );
};

Plugin.prototype.hudHide = async function(channel: string) {
  const result = await this.call(
    MethodHudHide,
    {
      channel,
    },
  );
};

Plugin.prototype.hudPush = async function(channel: string, fragments: unknown) {
  const result = await this.call(
    MethodHudPush,
    {
      channel,
      fragments,
    },
  );
};

Plugin.prototype.hudRemoveChannel = async function(channel: string) {
  const result = await this.call(
    MethodHudRemoveChannel,
    {
      channel,
    },
  );
  return result as HUDRemoveChannelResponse;
};

Plugin.prototype.hudSetSize = async function(channel: string, height: number) {
  const result = await this.call(
    MethodHudSetSize,
    {
      channel,
      height,
    },
  );
};

Plugin.prototype.hudShow = async function(channel: string) {
  const result = await this.call(
    MethodHudShow,
    {
      channel,
    },
  );
};

Plugin.prototype.inputClick = async function(button?: string) {
  const result = await this.call(
    MethodInputClick,
    {
      button,
    },
  );
};

Plugin.prototype.inputClipboardAction = async function(action: string, text?: unknown) {
  const result = await this.call(
    MethodInputClipboardAction,
    {
      action,
      text,
    },
  );
};

Plugin.prototype.inputClipboardRead = async function(contentType: string) {
  const result = await this.call(
    MethodInputClipboardRead,
    {
      content_type: contentType,
    },
  );
  return result as InputClipboardReadResponse;
};

Plugin.prototype.inputClipboardReadAll = async function() {
  const result = await this.call(MethodInputClipboardReadAll);
  return (result as any).items;
};

Plugin.prototype.inputClipboardWrite = async function(contentType: string, data: string) {
  const result = await this.call(
    MethodInputClipboardWrite,
    {
      content_type: contentType,
      data,
    },
  );
};

Plugin.prototype.inputClipboardWriteItems = async function(items?: ClipboardWriteItem[]) {
  const result = await this.call(
    MethodInputClipboardWriteItems,
    {
      items,
    },
  );
};

Plugin.prototype.inputDoubleClick = async function(x?: unknown, y?: unknown) {
  const result = await this.call(
    MethodInputDoubleClick,
    {
      x,
      y,
    },
  );
};

Plugin.prototype.inputDrag = async function(fromX: number, fromY: number, toX: number, toY: number, durationMs?: number) {
  const result = await this.call(
    MethodInputDrag,
    {
      from_x: fromX,
      from_y: fromY,
      to_x: toX,
      to_y: toY,
      duration_ms: durationMs,
    },
  );
};

Plugin.prototype.inputListInputSources = async function() {
  const result = await this.call(MethodInputListInputSources);
  return (result as any).sources;
};

Plugin.prototype.inputMouseButton = async function(direction: string, button?: string) {
  const result = await this.call(
    MethodInputMouseButton,
    {
      direction,
      button,
    },
  );
};

Plugin.prototype.inputPressKey = async function(code?: unknown, modifiers?: string[], name?: unknown) {
  const result = await this.call(
    MethodInputPressKey,
    {
      code,
      modifiers,
      name,
    },
  );
};

Plugin.prototype.inputRawKey = async function(code: number, direction: string) {
  const result = await this.call(
    MethodInputRawKey,
    {
      code,
      direction,
    },
  );
};

Plugin.prototype.inputRightClick = async function(x?: unknown, y?: unknown) {
  const result = await this.call(
    MethodInputRightClick,
    {
      x,
      y,
    },
  );
};

Plugin.prototype.inputScroll = async function(direction: string, amount?: number, unit?: string) {
  const result = await this.call(
    MethodInputScroll,
    {
      direction,
      amount,
      unit,
    },
  );
};

Plugin.prototype.inputSwitchInputSource = async function(sourceId: string) {
  const result = await this.call(
    MethodInputSwitchInputSource,
    {
      source_id: sourceId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.inputTypeText = async function(text: string) {
  const result = await this.call(
    MethodInputTypeText,
    {
      text,
    },
  );
};

Plugin.prototype.keyNamesSet = async function(names?: Record<string, number>) {
  const result = await this.call(
    MethodKeyNamesSet,
    {
      names,
    },
  );
  return result as KeyNamesSetResponse;
};

Plugin.prototype.keybindsRegister = async function(snapshot: unknown) {
  const result = await this.call(
    MethodKeybindsRegister,
    {
      snapshot,
    },
  );
  return result as KeybindsRegisterResponse;
};

Plugin.prototype.matchAliasesGet = async function() {
  const result = await this.call(MethodMatchAliasesGet);
  return result as MatchAliasesGetResponse;
};

Plugin.prototype.matchAliasesSet = async function(aliases?: Record<string, string>) {
  const result = await this.call(
    MethodMatchAliasesSet,
    {
      aliases,
    },
  );
  return result as MatchAliasesSetResponse;
};

Plugin.prototype.nativeActivateApp = async function(bundleId: string, allWindows?: boolean) {
  const result = await this.call(
    MethodNativeActivateApp,
    {
      bundle_id: bundleId,
      all_windows: allWindows,
    },
  );
};

Plugin.prototype.nativeActiveSpace = async function() {
  const result = await this.call(MethodNativeActiveSpace);
  return (result as any).active;
};

Plugin.prototype.nativeAppIcon = async function(bundleId: string, size?: number) {
  const result = await this.call(
    MethodNativeAppIcon,
    {
      bundle_id: bundleId,
      size,
    },
  );
  return result as NativeAppIconResponse;
};

Plugin.prototype.nativeAudioDevices = async function() {
  const result = await this.call(MethodNativeAudioDevices);
  return (result as any).devices;
};

Plugin.prototype.nativeAxElementAtPoint = async function(pid: number, x: number, y: number) {
  const result = await this.call(
    MethodNativeAxElementAtPoint,
    {
      pid,
      x,
      y,
    },
  );
  return result as NativeAxElementAtPointResponse;
};

Plugin.prototype.nativeAxElementTree = async function(element: AXElementRef, depth?: number) {
  const result = await this.call(
    MethodNativeAxElementTree,
    {
      element,
      depth,
    },
  );
  return result as AXElementNode;
};

Plugin.prototype.nativeAxObserve = async function(pid: number, notifications?: string[]) {
  const result = await this.call(
    MethodNativeAxObserve,
    {
      pid,
      notifications,
    },
  );
  return result as NativeAxObserveResponse;
};

Plugin.prototype.nativeAxPerformAction = async function(action: string, element: AXElementRef) {
  const result = await this.call(
    MethodNativeAxPerformAction,
    {
      action,
      element,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeAxReadAttributes = async function(element: AXElementRef, attributes?: string[]) {
  const result = await this.call(
    MethodNativeAxReadAttributes,
    {
      element,
      attributes,
    },
  );
};

Plugin.prototype.nativeAxSetAttribute = async function(attribute: string, element: AXElementRef, value: unknown) {
  const result = await this.call(
    MethodNativeAxSetAttribute,
    {
      attribute,
      element,
      value,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeAxUnobserve = async function(subscriptionId: string) {
  const result = await this.call(
    MethodNativeAxUnobserve,
    {
      subscription_id: subscriptionId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeBatchIsTileable = async function(windowIds?: string[]) {
  const result = await this.call(
    MethodNativeBatchIsTileable,
    {
      window_ids: windowIds,
    },
  );
  return (result as any).results;
};

Plugin.prototype.nativeBatchSetFrames = async function(frames?: WindowFrame[], readback?: boolean) {
  const result = await this.call(
    MethodNativeBatchSetFrames,
    {
      frames,
      readback,
    },
  );
  return (result as any).results;
};

Plugin.prototype.nativeBattery = async function() {
  const result = await this.call(MethodNativeBattery);
  return result as NativeBatteryResponse;
};

Plugin.prototype.nativeBleDiscoverServices = async function(deviceIdentifier: string) {
  const result = await this.call(
    MethodNativeBleDiscoverServices,
    {
      device_identifier: deviceIdentifier,
    },
  );
  return (result as any).services;
};

Plugin.prototype.nativeBleSubscribe = async function(characteristicUuid: string, deviceIdentifier: string, serviceUuid: string) {
  const result = await this.call(
    MethodNativeBleSubscribe,
    {
      characteristic_uuid: characteristicUuid,
      device_identifier: deviceIdentifier,
      service_uuid: serviceUuid,
    },
  );
  return result as NativeBleSubscribeResponse;
};

Plugin.prototype.nativeBleSubscribeAllThenWrite = async function(deviceIdentifier: string, subscribeServices?: string[], writes?: BleWriteEntry[]) {
  const result = await this.call(
    MethodNativeBleSubscribeAllThenWrite,
    {
      device_identifier: deviceIdentifier,
      subscribe_services: subscribeServices,
      writes,
    },
  );
  return result as NativeBleSubscribeAllThenWriteResponse;
};

Plugin.prototype.nativeBleWrite = async function(characteristicUuid: string, deviceIdentifier: string, serviceUuid: string, data?: number[], writeType?: string) {
  const result = await this.call(
    MethodNativeBleWrite,
    {
      characteristic_uuid: characteristicUuid,
      device_identifier: deviceIdentifier,
      service_uuid: serviceUuid,
      data,
      write_type: writeType,
    },
  );
  return result as NativeBleWriteResponse;
};

Plugin.prototype.nativeBluetoothDevices = async function() {
  const result = await this.call(MethodNativeBluetoothDevices);
  return (result as any).devices;
};

Plugin.prototype.nativeBorders = async function() {
  const result = await this.call(MethodNativeBorders);
};

Plugin.prototype.nativeBrightness = async function(displayId?: unknown) {
  const result = await this.call(
    MethodNativeBrightness,
    {
      display_id: displayId,
    },
  );
  return result as NativeBrightnessResponse;
};

Plugin.prototype.nativeCaptureWindow = async function(windowId: string) {
  const result = await this.call(
    MethodNativeCaptureWindow,
    {
      window_id: windowId,
    },
  );
  return result as NativeCaptureWindowResponse;
};

Plugin.prototype.nativeClickMenuItem = async function(pid: number, path?: string[]) {
  const result = await this.call(
    MethodNativeClickMenuItem,
    {
      pid,
      path,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeClipboardChangeCount = async function() {
  const result = await this.call(MethodNativeClipboardChangeCount);
  return result as NativeClipboardChangeCountResponse;
};

Plugin.prototype.nativeCloseWindow = async function(windowId: string) {
  const result = await this.call(
    MethodNativeCloseWindow,
    {
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeColorAtPoint = async function(x: number, y: number) {
  const result = await this.call(
    MethodNativeColorAtPoint,
    {
      x,
      y,
    },
  );
  return result as NativeColorAtPointResponse;
};

Plugin.prototype.nativeCurrentUser = async function() {
  const result = await this.call(MethodNativeCurrentUser);
  return result as NativeCurrentUserResponse;
};

Plugin.prototype.nativeCursor = async function() {
  const result = await this.call(MethodNativeCursor);
  return result as NativeCursorResponse;
};

Plugin.prototype.nativeCursorInfo = async function() {
  const result = await this.call(MethodNativeCursorInfo);
  return result as NativeCursorInfoResponse;
};

Plugin.prototype.nativeDarkMode = async function() {
  const result = await this.call(MethodNativeDarkMode);
  return result as NativeDarkModeResponse;
};

Plugin.prototype.nativeDefaultBrowser = async function() {
  const result = await this.call(MethodNativeDefaultBrowser);
  return result as NativeDefaultBrowserResponse;
};

Plugin.prototype.nativeDismissNotification = async function(id: string) {
  const result = await this.call(
    MethodNativeDismissNotification,
    {
      id,
    },
  );
};

Plugin.prototype.nativeDisplays = async function() {
  const result = await this.call(MethodNativeDisplays);
  return (result as any).displays;
};

Plugin.prototype.nativeDnd = async function() {
  const result = await this.call(MethodNativeDnd);
  return result as NativeDndResponse;
};

Plugin.prototype.nativeFileTags = async function(path: string, tags?: unknown) {
  const result = await this.call(
    MethodNativeFileTags,
    {
      path,
      tags,
    },
  );
};

Plugin.prototype.nativeForceQuitApp = async function(bundleId: string) {
  const result = await this.call(
    MethodNativeForceQuitApp,
    {
      bundle_id: bundleId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeFrontmostApp = async function() {
  const result = await this.call(MethodNativeFrontmostApp);
  return result as NativeFrontmostAppResponse;
};

Plugin.prototype.nativeGetWindowInfo = async function(windowId: string) {
  const result = await this.call(
    MethodNativeGetWindowInfo,
    {
      window_id: windowId,
    },
  );
  return result as NativeGetWindowInfoResponse;
};

Plugin.prototype.nativeHidClaim = async function(deviceId: string) {
  const result = await this.call(
    MethodNativeHidClaim,
    {
      device_id: deviceId,
    },
  );
  return result as NativeHidClaimResponse;
};

Plugin.prototype.nativeHidDevices = async function() {
  const result = await this.call(MethodNativeHidDevices);
  return (result as any).devices;
};

Plugin.prototype.nativeHidElements = async function(deviceId: string) {
  const result = await this.call(
    MethodNativeHidElements,
    {
      device_id: deviceId,
    },
  );
  return (result as any).elements;
};

Plugin.prototype.nativeHidRelease = async function(deviceId: string) {
  const result = await this.call(
    MethodNativeHidRelease,
    {
      device_id: deviceId,
    },
  );
  return result as NativeHidReleaseResponse;
};

Plugin.prototype.nativeHidSendReport = async function(deviceId: string, reportId: number, reportType: string, data?: number[]) {
  const result = await this.call(
    MethodNativeHidSendReport,
    {
      device_id: deviceId,
      report_id: reportId,
      report_type: reportType,
      data,
    },
  );
  return result as NativeHidSendReportResponse;
};

Plugin.prototype.nativeHideApp = async function(bundleId: string) {
  const result = await this.call(
    MethodNativeHideApp,
    {
      bundle_id: bundleId,
    },
  );
};

Plugin.prototype.nativeInstalledApps = async function() {
  const result = await this.call(MethodNativeInstalledApps);
  return (result as any).apps;
};

Plugin.prototype.nativeIsAppHidden = async function(bundleId: string) {
  const result = await this.call(
    MethodNativeIsAppHidden,
    {
      bundle_id: bundleId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeKeyboardLayout = async function() {
  const result = await this.call(MethodNativeKeyboardLayout);
  return result as NativeKeyboardLayoutResponse;
};

Plugin.prototype.nativeLaunchApp = async function(bundleId: string, newInstance?: boolean) {
  const result = await this.call(
    MethodNativeLaunchApp,
    {
      bundle_id: bundleId,
      new_instance: newInstance,
    },
  );
};

Plugin.prototype.nativeListNotifications = async function() {
  const result = await this.call(MethodNativeListNotifications);
  return (result as any).notifications;
};

Plugin.prototype.nativeListSpaces = async function() {
  const result = await this.call(MethodNativeListSpaces);
  return (result as any).spaces;
};

Plugin.prototype.nativeLoginItems = async function() {
  const result = await this.call(MethodNativeLoginItems);
  return (result as any).items;
};

Plugin.prototype.nativeMenuBar = async function(pid: number) {
  const result = await this.call(
    MethodNativeMenuBar,
    {
      pid,
    },
  );
  return (result as any).items;
};

Plugin.prototype.nativeMinimizeWindow = async function(windowId: string) {
  const result = await this.call(
    MethodNativeMinimizeWindow,
    {
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeMoveWindowToDisplay = async function(displayId: number, windowId: string) {
  const result = await this.call(
    MethodNativeMoveWindowToDisplay,
    {
      display_id: displayId,
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeMoveWindowToSpace = async function(spaceId: number, windowId: string) {
  const result = await this.call(
    MethodNativeMoveWindowToSpace,
    {
      space_id: spaceId,
      window_id: windowId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeMute = async function(muted: boolean) {
  const result = await this.call(
    MethodNativeMute,
    {
      muted,
    },
  );
};

Plugin.prototype.nativeNotify = async function(title: string, body?: unknown, sound?: unknown, subtitle?: unknown) {
  const result = await this.call(
    MethodNativeNotify,
    {
      title,
      body,
      sound,
      subtitle,
    },
  );
  return result as NativeNotifyResponse;
};

Plugin.prototype.nativeObserveWindows = async function(pid: number) {
  const result = await this.call(
    MethodNativeObserveWindows,
    {
      pid,
    },
  );
  return result as NativeObserveWindowsResponse;
};

Plugin.prototype.nativeOpenTarget = async function(target: string) {
  const result = await this.call(
    MethodNativeOpenTarget,
    {
      target,
    },
  );
};

Plugin.prototype.nativePlaySound = async function(name: string) {
  const result = await this.call(
    MethodNativePlaySound,
    {
      name,
    },
  );
};

Plugin.prototype.nativePollBurst = async function() {
  const result = await this.call(MethodNativePollBurst);
};

Plugin.prototype.nativePreventSleep = async function(assertionId?: unknown, reason?: string) {
  const result = await this.call(
    MethodNativePreventSleep,
    {
      assertion_id: assertionId,
      reason,
    },
  );
  return result as NativePreventSleepResponse;
};

Plugin.prototype.nativeQuickLook = async function(path: string, size?: number) {
  const result = await this.call(
    MethodNativeQuickLook,
    {
      path,
      size,
    },
  );
  return result as NativeQuickLookResponse;
};

Plugin.prototype.nativeQuitApp = async function(bundleId: string) {
  const result = await this.call(
    MethodNativeQuitApp,
    {
      bundle_id: bundleId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeRaiseWindow = async function(windowId: string) {
  const result = await this.call(
    MethodNativeRaiseWindow,
    {
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeRevealInFinder = async function(path: string) {
  const result = await this.call(
    MethodNativeRevealInFinder,
    {
      path,
    },
  );
};

Plugin.prototype.nativeRunApplescript = async function(script: string) {
  const result = await this.call(
    MethodNativeRunApplescript,
    {
      script,
    },
  );
  return result as NativeRunApplescriptResponse;
};

Plugin.prototype.nativeRunningApps = async function() {
  const result = await this.call(MethodNativeRunningApps);
  return (result as any).apps;
};

Plugin.prototype.nativeScreenLock = async function() {
  const result = await this.call(MethodNativeScreenLock);
};

Plugin.prototype.nativeScreenshot = async function(displayId?: unknown, region?: unknown, windowId?: unknown) {
  const result = await this.call(
    MethodNativeScreenshot,
    {
      display_id: displayId,
      region,
      window_id: windowId,
    },
  );
  return result as NativeScreenshotResponse;
};

Plugin.prototype.nativeSelectedFinderItems = async function() {
  const result = await this.call(MethodNativeSelectedFinderItems);
  return (result as any).paths;
};

Plugin.prototype.nativeSetAudioDevice = async function(deviceType: string, uid: string) {
  const result = await this.call(
    MethodNativeSetAudioDevice,
    {
      device_type: deviceType,
      uid,
    },
  );
};

Plugin.prototype.nativeSetBrightness = async function(brightness: number, displayId?: unknown) {
  const result = await this.call(
    MethodNativeSetBrightness,
    {
      brightness,
      display_id: displayId,
    },
  );
};

Plugin.prototype.nativeSetDarkMode = async function(dark: boolean) {
  const result = await this.call(
    MethodNativeSetDarkMode,
    {
      dark,
    },
  );
};

Plugin.prototype.nativeSetDnd = async function(enabled: boolean) {
  const result = await this.call(
    MethodNativeSetDnd,
    {
      enabled,
    },
  );
};

Plugin.prototype.nativeSetVolume = async function(volume: number) {
  const result = await this.call(
    MethodNativeSetVolume,
    {
      volume,
    },
  );
};

Plugin.prototype.nativeSetWindowAlpha = async function(alpha: number, windowId: string) {
  const result = await this.call(
    MethodNativeSetWindowAlpha,
    {
      alpha,
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeSetWindowLevel = async function(level: string, windowId: string) {
  const result = await this.call(
    MethodNativeSetWindowLevel,
    {
      level,
      window_id: windowId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeSpeak = async function(text: string, rate?: unknown, voice?: unknown) {
  const result = await this.call(
    MethodNativeSpeak,
    {
      text,
      rate,
      voice,
    },
  );
};

Plugin.prototype.nativeSpotlight = async function(query: string, limit?: number, scope?: unknown) {
  const result = await this.call(
    MethodNativeSpotlight,
    {
      query,
      limit,
      scope,
    },
  );
  return (result as any).results;
};

Plugin.prototype.nativeSystemUptime = async function() {
  const result = await this.call(MethodNativeSystemUptime);
  return result as NativeSystemUptimeResponse;
};

Plugin.prototype.nativeToggleFullscreen = async function(windowId: string) {
  const result = await this.call(
    MethodNativeToggleFullscreen,
    {
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeTrash = async function(path: string) {
  const result = await this.call(
    MethodNativeTrash,
    {
      path,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeUnhideApp = async function(bundleId: string) {
  const result = await this.call(
    MethodNativeUnhideApp,
    {
      bundle_id: bundleId,
    },
  );
};

Plugin.prototype.nativeUnminimizeWindow = async function(windowId: string) {
  const result = await this.call(
    MethodNativeUnminimizeWindow,
    {
      window_id: windowId,
    },
  );
};

Plugin.prototype.nativeUnobserveWindows = async function(subscriptionId: string) {
  const result = await this.call(
    MethodNativeUnobserveWindows,
    {
      subscription_id: subscriptionId,
    },
  );
  return (result as any).result;
};

Plugin.prototype.nativeVolume = async function() {
  const result = await this.call(MethodNativeVolume);
  return result as NativeVolumeResponse;
};

Plugin.prototype.nativeWarpCursor = async function(x: number, y: number) {
  const result = await this.call(
    MethodNativeWarpCursor,
    {
      x,
      y,
    },
  );
};

Plugin.prototype.nativeWifi = async function() {
  const result = await this.call(MethodNativeWifi);
  return result as NativeWifiResponse;
};

Plugin.prototype.nativeWorldModel = async function(onScreen?: boolean) {
  const result = await this.call(
    MethodNativeWorldModel,
    {
      on_screen: onScreen,
    },
  );
  return result as WorldModel;
};

Plugin.prototype.selectionPick = async function(index: number) {
  const result = await this.call(
    MethodSelectionPick,
    {
      index,
    },
  );
  return result as SelectionPickResponse;
};

Plugin.prototype.selectionSet = async function(channel?: unknown, items?: unknown, title?: unknown) {
  const result = await this.call(
    MethodSelectionSet,
    {
      channel,
      items,
      title,
    },
  );
};

Plugin.prototype.sessionEndCleanup = async function() {
  const result = await this.call(MethodSessionEndCleanup);
  return result as SessionEndCleanupResponse;
};

Plugin.prototype.settingsPatchSignals = async function(signals: string) {
  const result = await this.call(
    MethodSettingsPatchSignals,
    {
      signals,
    },
  );
};

Plugin.prototype.settingsRefresh = async function() {
  const result = await this.call(MethodSettingsRefresh);
};

Plugin.prototype.settingsRulesCreate = async function(newruleactionjson?: unknown, newruleactiontype?: unknown, newruleactionval?: unknown, newrulecategory?: unknown, newruleclearstags?: unknown, newruledescription?: unknown, newrulephrase?: unknown, newrulerequirestags?: unknown, newrulesetstags?: unknown) {
  const result = await this.call(
    MethodSettingsRulesCreate,
    {
      newruleactionjson,
      newruleactiontype,
      newruleactionval,
      newrulecategory,
      newruleclearstags,
      newruledescription,
      newrulephrase,
      newrulerequirestags,
      newrulesetstags,
    },
  );
};

Plugin.prototype.settingsRulesUpdate = async function(canonical: string, newruleactionjson?: unknown, newruleactiontype?: unknown, newruleactionval?: unknown, newrulecategory?: unknown, newruleclearstags?: unknown, newruledescription?: unknown, newrulephrase?: unknown, newrulerequirestags?: unknown, newrulesetstags?: unknown) {
  const result = await this.call(
    MethodSettingsRulesUpdate,
    {
      canonical,
      newruleactionjson,
      newruleactiontype,
      newruleactionval,
      newrulecategory,
      newruleclearstags,
      newruledescription,
      newrulephrase,
      newrulerequirestags,
      newrulesetstags,
    },
  );
};

Plugin.prototype.systemLaunchApp = async function(bundleId: string, newInstance?: boolean) {
  const result = await this.call(
    MethodSystemLaunchApp,
    {
      bundle_id: bundleId,
      new_instance: newInstance,
    },
  );
};

Plugin.prototype.systemNotify = async function(body: string, title: string, durationSecs?: unknown) {
  const result = await this.call(
    MethodSystemNotify,
    {
      body,
      title,
      duration_secs: durationSecs,
    },
  );
};

Plugin.prototype.systemRunShell = async function(command: string) {
  const result = await this.call(
    MethodSystemRunShell,
    {
      command,
    },
  );
};

Plugin.prototype.tagsGet = async function() {
  const result = await this.call(MethodTagsGet);
  return (result as any).tags;
};

Plugin.prototype.tagsModify = async function(clear?: string[], clearScoped?: boolean, set?: string[]) {
  const result = await this.call(
    MethodTagsModify,
    {
      clear,
      clear_scoped: clearScoped,
      set,
    },
  );
  return (result as any).tags;
};
