// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventAudioChunk = "audio_chunk" as const;
export const EventAudioDeviceAdded = "audio_device_added" as const;
export const EventAudioDeviceDefaultChanged = "audio_device_default_changed" as const;
export const EventAudioDeviceRemoved = "audio_device_removed" as const;
export const EventAudioDeviceSnapshot = "audio_device_snapshot" as const;
export const EventAudioStart = "audio_start" as const;
export const EventAudioStop = "audio_stop" as const;
export const EventCapability = "capability" as const;
export const EventDisplayAdded = "display_added" as const;
export const EventDisplayChanged = "display_changed" as const;
export const EventDisplayRemoved = "display_removed" as const;
export const EventDisplaySnapshot = "display_snapshot" as const;
export const EventError = "error" as const;
export const EventFlowCredit = "flow_credit" as const;
export const EventHeadingUpdate = "heading_update" as const;
export const EventLocationError = "location_error" as const;
export const EventLocationUpdate = "location_update" as const;
export const EventPowerSnapshot = "power_snapshot" as const;
export const EventPowerSourceChanged = "power_source_changed" as const;
export const EventTranscript = "transcript" as const;
export const EventVocabularyUpdate = "vocabulary_update" as const;

/**
 * The open namespace a stage emits custom events under: at least three
 * non-empty dot segments, `ext.<vendor>.<name>`.
 */
export const EXT_EVENT_PREFIX = "ext." as const;

/** Is this custom event type well-formed? */
export function isValidExtEventType(t: string): boolean {
  if (!t.startsWith(EXT_EVENT_PREFIX)) return false;
  const parts = t.split(".");
  return parts.length >= 3 && parts.every((p) => p.length > 0);
}

/**
 * Environment variables the platform sets when it spawns a stage.
 * NEVER re-derive these paths: the sandbox grants access by the path the
 * platform computed, so a second spelling is a denial that reads like a
 * missing directory.
 */
export const MODELS_DIR_ENV = "BRANCHKIT_MODELS_DIR" as const;
export const DATA_DIR_ENV = "BRANCHKIT_STAGE_DATA" as const;

export interface AudioChunk {
  session_id: string;
  timestamp_ms: number;
}

export interface AudioDeviceAdded {
  device: AudioDeviceInfo;
}

export interface AudioDeviceDefaultChanged {
  device_id: number;
  direction: string;
  name: string;
  uid: string;
}

export interface AudioDeviceInfo {
  device_id: number;
  is_default_input: boolean;
  is_default_output: boolean;
  is_input: boolean;
  is_output: boolean;
  name: string;
  uid: string;
}

export interface AudioDeviceRemoved {
  device_id: number;
  name: string;
  uid: string;
}

export interface AudioDeviceSnapshot {
  devices: AudioDeviceInfo[];
}

export interface AudioFormat {
  channels: number;
  rate: number;
  width: number;
}

export interface AudioStart {
  format: AudioFormat;
  session_id: string;
}

export interface AudioStop {
  /**
   * Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
   * which buffered audio must NOT be processed. Set when the stop was
   * triggered by an event whose audio position is known — the dictation
   * stop phrase (notes/DESIGN_DICTATION_AUDIO_CUTOFF.md). A source stage
   * forwards it verbatim on its downstream AudioStop; batch consumers
   * (whisperkit) truncate their buffer at it; absent = process everything.
   */
  cutoff_ms?: number;
  session_id: string;
}

export interface Capability {
  audio_formats?: AudioFormat[];
  /**
   * Event types this stage emits — built-in tags (`transcript`,
   * `power_snapshot`, …) and/or custom types under [`EXT_EVENT_PREFIX`]
   * (an `ext.<vendor>.*` glob covers a vendor namespace). Advisory at
   * runtime (the platform logs undeclared `ext.*` emissions rather than
   * dropping them); enforced by the conformance harness. Empty = the
   * stage declares nothing (pre-existing stages).
   */
  emits?: string[];
  feature_flags?: Record<string, unknown>;
  lifecycle_modes: string[];
  stage_name: string;
  stage_type: string;
}

export interface DisplayAdded {
  display: DisplayInfo;
}

export interface DisplayChanged {
  display: DisplayInfo;
}

export interface DisplayInfo {
  display_id: number;
  height: number;
  is_builtin: boolean;
  is_main: boolean;
  refresh_rate: number;
  scale_factor: number;
  width: number;
}

export interface DisplayRemoved {
  display_id: number;
}

export interface DisplaySnapshot {
  displays: DisplayInfo[];
}

export interface ErrorEvent {
  code: string;
  fatal: boolean;
  message: string;
  session_id?: string;
}

export interface FlowCredit {
  frames: number;
  session_id: string;
}

/**
 * The engine-facing wire projection of the compiled grammar DAG (Phase D2
 * contract).
 *
 * This is the JSON the actuator attaches to a `vocabulary_update` and the CTC
 * stage feeds to the patched `GrammarBuilder` to build `G`. It is a *reduced*
 * view of the DAG — exactly what FST construction needs, nothing the matcher
 * keeps:
 * - `start` (always 0) is `G`'s start AND its sole base accept state: every
 *   command-final arc returns there, so accepting at `start` accepts any
 *   sequence of complete commands.
 * - `arcs` are word-level `(from → word → to)` transitions; the builder maps
 *   `word` to the same word id `H ∘ L` emits and rides `weight` onto the arc.
 * - `open_states` are states whose continuation D1 could not enumerate (free
 *   text, dependent capture, list repeat/optional). The builder realizes each
 *   as final + a self-loop over the full word alphabet (the back-arc into a
 *   word loop), so those commands still recognize their open tail.
 *
 * D3 extends this with per-arc command ids; D2 carries words only.
 */
export interface GrammarDagWire {
  arcs: WireArc[];
  /**
   * Alternatives the compiler dropped under the empty-list policy —
   * telemetry only, the FST builder ignores it.
   */
  dropped_alts?: number;
  num_states: number;
  open_states?: OpenState[];
  start: number;
}

export interface HeadingUpdate {
  heading_accuracy: number;
  magnetic_heading: number;
  timestamp: number;
  true_heading: number;
}

export interface LocationError {
  code: string;
  message: string;
}

export interface LocationUpdate {
  altitude: number;
  horizontal_accuracy: number;
  latitude: number;
  longitude: number;
  timestamp: number;
  vertical_accuracy: number;
}

/**
 * A state whose continuation D1 could not fully enumerate. The builder realizes
 * it as final + a self-loop. `alphabet` bounds that self-loop when known;
 * omitted (`None`) means loop over the full recognition union — the phase-2
 * default and the always-safe fallback.
 */
export interface OpenState {
  alphabet?: string[];
  state: number;
}

export interface PowerSnapshot {
  state: PowerState;
}

export interface PowerSourceChanged {
  state: PowerState;
}

export interface PowerState {
  battery_level?: number;
  is_charging: boolean;
  source: string;
  time_to_empty?: number;
  time_to_full?: number;
}

export interface Transcript {
  /**
   * Coarse scalar confidence for the whole transcript — the MEAN of
   * `word_scores` on the sherpa CTC path, or an engine's own scalar where it
   * has no per-word signal. Deliberately coarse: a confidence GATE must read
   * `word_scores` (the min margin), never this. The mean hides a single
   * deeply-coerced word — a decode scoring [+8, -3] means +2.5 and sails past
   * a mean threshold the min-based data says should fail
   * (notes/DESIGN_ENGINE_POSTERIORS.md). For display/logging only.
   */
  confidence?: number;
  final: boolean;
  partial: boolean;
  session_id: string;
  text: string;
  /**
   * Shared-clock onset (ms, the AudioChunk timestamp_ms timebase) of each
   * word of `text`, aligned 1:1 with its whitespace-split words. Emitted by
   * engines with alignment (sherpa's CTC path); lets a consumer convert a
   * word position into an audio position that is meaningful to OTHER
   * concurrently-running pipelines — the dictation stop-phrase audio
   * cutoff (notes/DESIGN_DICTATION_AUDIO_CUTOFF.md).
   */
  word_onsets_ms?: number[];
  /**
   * Per-word acoustic score, aligned 1:1 with `text`'s whitespace-split
   * words (same alignment contract as `word_onsets_ms`). On the sherpa CTC
   * path this is the word's min token argmax-margin: positive = the audio
   * supported the word, negative = the closed grammar coerced it
   * (notes/DESIGN_ENGINE_POSTERIORS.md). When present, `confidence` is the
   * mean of these. Log-only today — enforcement gates land per-consumer
   * once field distributions are measured.
   */
  word_scores?: number[];
}

/**
 * The `vocabulary_update` payload: the recognition word union plus the
 * optional grammar stamps the platform attaches at delivery time.
 *
 * This struct is the typed contract; the actuator's producer side still
 * assembles the payload field-by-field (the three delivery-time grammar
 * stamps mutate the JSON per event), and an actuator-side test pins that
 * assembly to this shape so the two cannot drift silently. A consumer
 * stage should treat every field but `words` as optional and fall back
 * to the flat word list when a stamp is absent or malformed.
 */
export interface VocabularyUpdate {
  /**
   * The structured word-level grammar DAG (D2), stamped when the
   * structured-grammar toggle is on. Absent/null → the consumer falls back
   * to the flat word-list grammar.
   */
  grammar_dag?: unknown;
  /**
   * Exclusive-mode narrowing: when present, the engine grammar is built
   * from THIS list instead of `words`.
   */
  narrow_to?: string[];
  /**
   * Sparse per-word decoding bias (Lever E): only biased words appear;
   * everything else is neutral. Keyed by word identity so it cannot drift
   * out of alignment with the separately-built union.
   */
  word_weights?: Record<string, number>;
  /**
   * The full recognition word union (uppercased downstream to the model
   * lexicon's casing by the consumer).
   */
  words: string[];
}

/**
 * One word-level arc in [`GrammarDagWire`]. `weight` is omitted when absent
 * (D1 leaves it unset; a later weight policy populates it).
 */
export interface WireArc {
  from: number;
  to: number;
  weight?: number;
  word: string;
}

/**
 * The serialized header line — one JSON object per event, newline-terminated,
 * followed by exactly `payload_length` raw bytes when non-zero. `data` is
 * omitted when empty/null; `payload_length` is omitted when zero.
 */
export interface WireHeader {
  data?: unknown;
  payload_length?: number;
  type: string;
}

