// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// Recognition vocabulary: transcripts, the word union, and the
// command-grammar DAG a recognizer decodes against. Import this only if
// you are building a speech recognizer or an STT stage.

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventTranscript = "transcript" as const;
export const EventVocabularyUpdate = "vocabulary_update" as const;

/**
 * The engine-facing wire projection of the compiled grammar DAG (Phase D2
 * contract).
 *
 * This is the JSON the actuator attaches to a `vocabulary_update` and the CTC
 * stage feeds to the patched `GrammarBuilder` to build `G`. It is a *reduced*
 * view of the DAG — exactly what FST construction needs, nothing the matcher
 * keeps:
 * - `start` (always 0) is `G`'s start AND its sole base accept state: every
 *   command-final arc returns there, so accepting at `start` accepts any
 *   sequence of complete commands.
 * - `arcs` are word-level `(from → word → to)` transitions; the builder maps
 *   `word` to the same word id `H ∘ L` emits and rides `weight` onto the arc.
 * - `open_states` are states whose continuation D1 could not enumerate (free
 *   text, dependent capture, list repeat/optional). The builder realizes each
 *   as final + a self-loop over the full word alphabet (the back-arc into a
 *   word loop), so those commands still recognize their open tail.
 *
 * D3 extends this with per-arc command ids; D2 carries words only.
 */
export interface GrammarDagWire {
  arcs: WireArc[];
  /**
   * Alternatives the compiler dropped under the empty-list policy —
   * telemetry only, the FST builder ignores it.
   */
  dropped_alts?: number;
  num_states: number;
  open_states?: OpenState[];
  start: number;
}

/**
 * A state whose continuation D1 could not fully enumerate. The builder realizes
 * it as final + a self-loop. `alphabet` bounds that self-loop when known;
 * omitted (`None`) means loop over the full recognition union — the phase-2
 * default and the always-safe fallback.
 */
export interface OpenState {
  alphabet?: string[];
  state: number;
}

export interface Transcript {
  /**
   * Coarse scalar confidence for the whole transcript: the MEAN of
   * `word_scores` when the engine produces them, or its own scalar when it
   * has no per-word signal.
   *
   * Deliberately coarse, and the reason matters — **a confidence GATE must
   * read `word_scores` (the minimum), never this.** A mean hides a single
   * badly-supported word: scores of [+8, -3] average to +2.5 and sail past
   * a threshold the per-word data says should fail. For display and
   * logging only.
   */
  confidence?: number;
  final: boolean;
  partial: boolean;
  session_id: string;
  text: string;
  /**
   * Shared-clock onset (ms, the AudioChunk `timestamp_ms` timebase) of each
   * word of `text`, aligned 1:1 with its whitespace-split words. Emitted by
   * engines that produce alignment; omitted by those that do not.
   *
   * Because the timebase is the shared clock rather than a per-session
   * counter, a consumer can convert a word position into an audio position
   * that is meaningful to OTHER concurrently-running pipelines — which is
   * what makes `AudioStop::cutoff_ms` possible across pipelines.
   */
  word_onsets_ms?: number[];
  /**
   * Per-word acoustic score, aligned 1:1 with `text`'s whitespace-split
   * words (same alignment contract as `word_onsets_ms`).
   *
   * Sign is the contract; magnitude is the engine's own scale. Positive
   * means the audio supported the word. Negative means the decoder's
   * language constraint outweighed weak acoustic evidence — the word was
   * produced because the grammar allowed it, not because it was heard. A
   * stage that computes these should document its own scale; a consumer
   * that gates on them should read the MINIMUM, per `confidence` above.
   *
   * When present, `confidence` is the mean of these.
   */
  word_scores?: number[];
}

/**
 * The `vocabulary_update` payload: the recognition word union plus the
 * optional grammar stamps the platform attaches at delivery time.
 *
 * This struct is the typed contract; the actuator's producer side still
 * assembles the payload field-by-field (the three delivery-time grammar
 * stamps mutate the JSON per event), and an actuator-side test pins that
 * assembly to this shape so the two cannot drift silently. A consumer
 * stage should treat every field but `words` as optional and fall back
 * to the flat word list when a stamp is absent or malformed.
 */
export interface VocabularyUpdate {
  /**
   * The structured word-level grammar DAG (D2), stamped when the
   * structured-grammar toggle is on. Absent/null → the consumer falls back
   * to the flat word-list grammar.
   */
  grammar_dag?: unknown;
  /**
   * Exclusive-mode narrowing: when present, the engine grammar is built
   * from THIS list instead of `words`.
   */
  narrow_to?: string[];
  /**
   * Sparse per-word decoding bias (Lever E): only biased words appear;
   * everything else is neutral. Keyed by word identity so it cannot drift
   * out of alignment with the separately-built union.
   */
  word_weights?: Record<string, number>;
  /**
   * The full recognition word union (uppercased downstream to the model
   * lexicon's casing by the consumer).
   */
  words: string[];
}

/**
 * One word-level arc in [`GrammarDagWire`]. `weight` is omitted when absent
 * (D1 leaves it unset; a later weight policy populates it).
 */
export interface WireArc {
  from: number;
  to: number;
  weight?: number;
  word: string;
}

