// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// The audio session vocabulary. Import this if your stage produces or
// consumes an audio stream.

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventAudioChunk = "audio_chunk" as const;
export const EventAudioStart = "audio_start" as const;
export const EventAudioStop = "audio_stop" as const;

export interface AudioChunk {
  session_id: string;
  timestamp_ms: number;
}

export interface AudioFormat {
  channels: number;
  rate: number;
  width: number;
}

export interface AudioStart {
  format: AudioFormat;
  session_id: string;
}

export interface AudioStop {
  /**
   * Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
   * which buffered audio must NOT be processed. Set when the stop was
   * triggered by something whose audio position is known — a recognized
   * stop phrase, say — so that a consumer buffering ahead of the trigger
   * does not process audio the user never meant to send.
   *
   * A source stage forwards it verbatim on its downstream AudioStop; a
   * batch consumer truncates its buffer at it; absent = process
   * everything.
   */
  cutoff_ms?: number;
  session_id: string;
}

