// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// Transport vocabulary: the handshake, framing, error and flow-credit
// types every stage speaks whatever its domain.

import type { AudioFormat } from "./pipeline_events_audio_gen.js";
export type { AudioFormat };

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventCapability = "capability" as const;
export const EventError = "error" as const;
export const EventFlowCredit = "flow_credit" as const;

/**
 * The open namespace a stage emits custom events under: at least three
 * non-empty dot segments, `ext.<vendor>.<name>`.
 *
 * This is the namespace EVERY domain the platform does not itself decode
 * lives in — a foot pedal, a frame source, a MIDI filter. It needs no
 * platform change and no entry in any catalog.
 */
export const EXT_EVENT_PREFIX = "ext." as const;

/** Is this custom event type well-formed? */
export function isValidExtEventType(t: string): boolean {
  if (!t.startsWith(EXT_EVENT_PREFIX)) return false;
  const parts = t.split(".");
  return parts.length >= 3 && parts.every((p) => p.length > 0);
}

/**
 * Environment variables the platform sets when it spawns a stage.
 * NEVER re-derive these paths: the sandbox grants access by the path the
 * platform computed, so a second spelling is a denial that reads like a
 * missing directory.
 */
export const MODELS_DIR_ENV = "BRANCHKIT_MODELS_DIR" as const;
export const DATA_DIR_ENV = "BRANCHKIT_STAGE_DATA" as const;

export interface Capability {
  audio_formats?: AudioFormat[];
  /**
   * Custom event types this stage accepts from the stage ABOVE it in a
   * pipeline — exact `ext.<vendor>.<name>` types, or `ext.<vendor>.*`
   * globs.
   *
   * This is the stage-to-stage valve. The typed families (`audio_*`,
   * `transcript`) always flow to the next stage and need no declaration;
   * `ext.*` events do not, because the platform's default for a vocabulary
   * it cannot decode is to hop it onto the event bus. Declaring a type here
   * says "send it to me instead", which is what lets two stages agree on a
   * vocabulary the platform knows nothing about — frames, MIDI, sensor
   * readings, anything.
   *
   * Checked when the pipeline is wired: a declared type its upstream
   * neighbour does not emit is a mis-wire and fails loudly, rather than
   * leaving the stage waiting for something that can never arrive.
   *
   * Forwarded events are NOT also published to the bus — downstream
   * delivery replaces it. Backpressure on them is the pipe's, not the
   * credit window's: a flooding producer blocks on the OS buffer. The
   * windowed credit that `audio_chunk` gets buys abort and visibility on
   * top of that, and no custom vocabulary has needed it yet.
   */
  consumes?: string[];
  /**
   * Event types this stage emits — built-in tags (`transcript`,
   * `power_snapshot`, …) and/or custom types under [`EXT_EVENT_PREFIX`]
   * (an `ext.<vendor>.*` glob covers a vendor namespace). Advisory at
   * runtime (the platform logs undeclared `ext.*` emissions rather than
   * dropping them); enforced by the conformance harness. Empty = the
   * stage declares nothing (pre-existing stages).
   */
  emits?: string[];
  feature_flags?: Record<string, unknown>;
  lifecycle_modes: string[];
  stage_name: string;
  stage_type: string;
}

export interface ErrorEvent {
  code: string;
  fatal: boolean;
  message: string;
  session_id?: string;
}

export interface FlowCredit {
  frames: number;
  session_id: string;
}

/**
 * The serialized header line — one JSON object per event, newline-terminated,
 * followed by exactly `payload_length` raw bytes when non-zero. `data` is
 * omitted when empty/null; `payload_length` is omitted when zero.
 */
export interface WireHeader {
  data?: unknown;
  payload_length?: number;
  type: string;
}

