// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// First-party monitor families. Typed because the platform renames them
// onto its bus as `_platform.*` events; a third-party monitor uses
// `ext.<vendor>.*` instead and needs nothing from here.

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventAudioDeviceAdded = "audio_device_added" as const;
export const EventAudioDeviceDefaultChanged = "audio_device_default_changed" as const;
export const EventAudioDeviceRemoved = "audio_device_removed" as const;
export const EventAudioDeviceSnapshot = "audio_device_snapshot" as const;
export const EventDisplayAdded = "display_added" as const;
export const EventDisplayChanged = "display_changed" as const;
export const EventDisplayRemoved = "display_removed" as const;
export const EventDisplaySnapshot = "display_snapshot" as const;
export const EventHeadingUpdate = "heading_update" as const;
export const EventLocationError = "location_error" as const;
export const EventLocationUpdate = "location_update" as const;
export const EventPowerSnapshot = "power_snapshot" as const;
export const EventPowerSourceChanged = "power_source_changed" as const;

export interface AudioDeviceAdded {
  device: AudioDeviceInfo;
}

export interface AudioDeviceDefaultChanged {
  device_id: number;
  direction: string;
  name: string;
  uid: string;
}

export interface AudioDeviceInfo {
  device_id: number;
  is_default_input: boolean;
  is_default_output: boolean;
  is_input: boolean;
  is_output: boolean;
  name: string;
  uid: string;
}

export interface AudioDeviceRemoved {
  device_id: number;
  name: string;
  uid: string;
}

export interface AudioDeviceSnapshot {
  devices: AudioDeviceInfo[];
}

export interface DisplayAdded {
  display: DisplayInfo;
}

export interface DisplayChanged {
  display: DisplayInfo;
}

export interface DisplayInfo {
  display_id: number;
  height: number;
  is_builtin: boolean;
  is_main: boolean;
  refresh_rate: number;
  scale_factor: number;
  width: number;
}

export interface DisplayRemoved {
  display_id: number;
}

export interface DisplaySnapshot {
  displays: DisplayInfo[];
}

export interface HeadingUpdate {
  heading_accuracy: number;
  magnetic_heading: number;
  timestamp: number;
  true_heading: number;
}

export interface LocationError {
  code: string;
  message: string;
}

export interface LocationUpdate {
  altitude: number;
  horizontal_accuracy: number;
  latitude: number;
  longitude: number;
  timestamp: number;
  vertical_accuracy: number;
}

export interface PowerSnapshot {
  state: PowerState;
}

export interface PowerSourceChanged {
  state: PowerState;
}

export interface PowerState {
  battery_level?: number;
  is_charging: boolean;
  source: string;
  time_to_empty?: number;
  time_to_full?: number;
}

