// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// The audio session vocabulary. Import this if your stage produces or
// consumes an audio stream — a speech engine (`speak` in, audio out) and an
// audio sink (audio in, `playback_*` out) included.

/** Wire event tags. Use instead of string literals so vocabulary drift is a type error. */
export const EventAudioChunk = "audio_chunk" as const;
export const EventAudioStart = "audio_start" as const;
export const EventAudioStop = "audio_stop" as const;
export const EventPlaybackEnded = "playback_ended" as const;
export const EventPlaybackStarted = "playback_started" as const;
export const EventSpeak = "speak" as const;

export interface AudioChunk {
  session_id: string;
  timestamp_ms: number;
}

export interface AudioFormat {
  channels: number;
  rate: number;
  width: number;
}

export interface AudioStart {
  format: AudioFormat;
  session_id: string;
}

export interface AudioStop {
  /**
   * Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
   * which buffered audio must NOT be processed. Set when the stop was
   * triggered by something whose audio position is known — a recognized
   * stop phrase, say — so that a consumer buffering ahead of the trigger
   * does not process audio the user never meant to send.
   *
   * A source stage forwards it verbatim on its downstream AudioStop; a
   * batch consumer truncates its buffer at it; absent = process
   * everything.
   */
  cutoff_ms?: number;
  session_id: string;
}

/**
 * `playback_ended`: an audio session's last sound left the speakers, or it
 * was cut off.
 */
export interface PlaybackEnded {
  /**
   * When, on the shared clock (as `playback_started`'s `at_ms`).
   */
  at_ms: number;
  /**
   * True when playback was stopped before the audio ran out.
   */
  interrupted?: boolean;
  session_id: string;
}

/**
 * `playback_started`: an audio session's first sound left the speakers.
 *
 * Emitted by an audio sink (`stage_type` `speaker`) — the stage that plays
 * audio rather than processing it — so the platform knows exactly when the
 * person, and the microphone, began to hear it.
 */
export interface PlaybackStarted {
  /**
   * When, on the shared clock (the `AudioChunk` `timestamp_ms` timebase,
   * which each SDK's stage runtime reads for you). Comparable with the
   * onsets a recognizer
   * reports, which is what lets the platform drop its own voice coming
   * back through the microphone.
   */
  at_ms: number;
  session_id: string;
}

/**
 * The `speak` request: say these words. Sent by the platform to a speech
 * engine (`stage_type` `tts`), one per utterance.
 *
 * The engine answers on the same `session_id` with the audio session
 * vocabulary, run the other way: `audio_start` (its format), `audio_chunk`s
 * as it synthesizes — streaming, so the first words play while the rest are
 * still being made — and exactly one `audio_stop` when the utterance is
 * over, whether it finished, failed (an `error` with this `session_id`
 * first) or was cancelled. Every request gets that one `audio_stop`, even
 * one cancelled before it started, so the platform never waits on an
 * utterance that will not come.
 *
 * Cancel is an inbound `audio_stop` naming the session: the engine stops
 * producing for it at once and closes it. Requests are spoken in the order
 * they arrive; which utterance goes first, and what cuts in, is the
 * platform's decision, not the engine's.
 */
export interface Speak {
  /**
   * BCP 47 tag of the language `text` is in, when the caller knows it. An
   * engine with voices in several languages may use it to pick one when no
   * voice is named.
   */
  locale?: string;
  /**
   * Pace relative to the voice's own: 1.0 is normal, 2.0 twice as fast.
   * Absent → 1.0. An engine that cannot change pace speaks at 1.0.
   */
  rate?: number;
  /**
   * The utterance. Every event the engine sends about it carries this.
   */
  session_id: string;
  /**
   * The words, plain text without markup, read as written.
   */
  text: string;
  /**
   * The `id` of one of the engine's `voices` (its capability). Absent, or
   * not one the engine declared → its default voice (the first declared).
   */
  voice?: string;
}

