// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

// ===== Shared types (from components/schemas) =====

export interface AXElementInfo {
  actions: string[];
  attributes: string[];
  children_count: number;
  description?: unknown;
  enabled: boolean;
  focused: boolean;
  path: AXPathSegment[];
  position?: unknown;
  role: string;
  size?: unknown;
  subrole?: unknown;
  title?: unknown;
  value?: unknown;
}

export interface AXElementNode {
  children: AXElementNode[];
  element: AXElementInfo;
}

export interface AXElementRef {
  path: AXPathSegment[];
  pid: number;
}

export interface AXPathSegment {
  index: number;
  role: string;
}

export interface ActiveSpace {
  display_id: number;
  space_id: number;
}

export interface AudioDevice {
  id: number;
  is_default_input: boolean;
  is_default_output: boolean;
  is_input: boolean;
  is_output: boolean;
  name: string;
  uid: string;
}

export interface BluetoothDevice {
  address: string;
  device_type?: unknown;
  is_connected: boolean;
  is_paired: boolean;
  name: string;
}

export interface ClipboardContents {
  available_types: string[];
  content_type: string;
  file_urls?: unknown;
  image_base64?: unknown;
  text?: unknown;
}

export interface ClipboardWriteItem {
  content_type: string;
  file_urls?: unknown;
  image_base64?: unknown;
  text?: unknown;
}

export interface CollectionsListItem {
  id: string;
  subtitle?: unknown;
  title: string;
}

export interface CollectionsListSection {
  entry_count: number;
  items: CollectionsListItem[];
  label: string;
  name: string;
  plugin: string;
}

export interface DeliveredNotification {
  body?: unknown;
  delivered_at: string;
  id: string;
  title: string;
}

export interface DiscoverItem {
  id: string;
  subtitle?: unknown;
  tag: string;
  title: string;
}

export interface DisplayInfo {
  h: number;
  id: number;
  visible_h: number;
  visible_w: number;
  visible_x: number;
  visible_y: number;
  w: number;
  x: number;
  y: number;
}

export interface DisplayMetadata {
  display_id: number;
  h: number;
  is_builtin: boolean;
  is_primary: boolean;
  name: string;
  refresh_rate: number;
  resolution_h: number;
  resolution_w: number;
  scale_factor: number;
  visible_h: number;
  visible_w: number;
  visible_x: number;
  visible_y: number;
  w: number;
  x: number;
  y: number;
}

export interface Frame {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface HudItem {
  icon?: string;
  id: string;
  subtitle?: string;
  tag?: string;
  title: string;
}

export interface HudResponse {
  content_html?: string;
  footer: string;
  sections?: HudSection[];
  title: string;
}

export interface HudSection {
  items: HudItem[];
  title: string;
}

export interface IngestSegmentSpec {
  alternatives: string[];
  duration: number;
  id: number;
  start: number;
  text: string;
}

export interface InputSource {
  id: string;
  is_active: boolean;
  name: string;
}

export interface InstalledApp {
  bundle_id: string;
  name: string;
}

export interface ListCommandItem {
  id: string;
  subtitle?: unknown;
  tag?: unknown;
  title: string;
}

export interface ListCommandSection {
  items: ListCommandItem[];
  title: string;
}

export interface LoginItem {
  bundle_id?: unknown;
  hidden: boolean;
  name: string;
  path: string;
}

export interface MenuItem {
  children: MenuItem[];
  enabled: boolean;
  index: number;
  shortcut?: unknown;
  title: string;
}

/**
 * How contributions to a shared store are merged when read.
 */
export type MergeStrategy = "authoritative" | "collect" | "keyed";

export type OnActionStatus = "ok" | "error" | "not_handled";

export interface RunningApp {
  bundle_id?: unknown;
  is_active: boolean;
  is_hidden: boolean;
  name: string;
  pid: number;
}

export interface ScreenshotRegion {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface SelectionItemSpec {
  id: string;
  tag?: string;
}

export interface SpaceInfo {
  display_id: number;
  is_active: boolean;
  space_id: number;
  space_type: string;
}

export interface SpotlightResult {
  kind: string;
  modified: string;
  name: string;
  path: string;
  size?: unknown;
}

export interface TileableEntry {
  tileable: boolean;
  window_id: string;
}

export interface WindowBounds {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface WindowFrame {
  h: number;
  w: number;
  window_id: string;
  x: number;
  y: number;
}

export interface WindowInfo {
  app_id: string;
  app_name: string;
  h: number;
  id: string;
  source: string;
  title: string;
  w: number;
  x: number;
  y: number;
}

export interface WorldModel {
  active_app?: string;
  active_window_id?: string;
  displays: DisplayInfo[];
  keyboard_layout_id: string;
  windows: WindowInfo[];
}

// ===== Plugin → Actuator request/response types =====

export interface CollectionDeleteRequest {
  name: string;
}

export interface CollectionDeleteResponse {
  ok: boolean;
}

export interface CollectionGetRequest {
  name: string;
}

export interface CollectionGetResponse {
  data: unknown;
  entries?: unknown;
  introducer: string;
  merge: MergeStrategy;
  name: string;
}

export interface CollectionOverrideRequest {
  action: string;
  collection: string;
  fields?: unknown;
  id?: unknown;
}

export interface CollectionOverrideResponse {
  ok: boolean;
}

export interface CollectionPushRequest {
  data: unknown;
  label?: unknown;
  name: string;
}

export interface CollectionPushResponse {
  ok: boolean;
}

export interface CollectionsListRequest {
  kind?: unknown;
}

export interface CollectionsListResponse {
  sections: CollectionsListSection[];
}

export interface CommandsDiscoverRequest {
  active_tags?: unknown;
  require_tag?: unknown;
  words?: unknown;
}

export interface CommandsDiscoverResponse {
  items: DiscoverItem[];
  title: string;
}

export interface CommandsHasPartialRequest {
  active_tags?: unknown;
  words?: string[];
}

export interface CommandsHasPartialResponse {
  has_partial: boolean;
  next_list?: unknown;
}

export interface CommandsListResponse {
  footer: string;
  sections: ListCommandSection[];
  title: string;
}

export interface CommandsMatchRequest {
  active_tags?: unknown;
  words?: string[];
}

export interface CommandsMatchResponse {
  action?: unknown;
  args: unknown[];
  clears_tags: string[];
  consumed_count: number;
  matched: boolean;
  owner_plugin?: unknown;
  requires_tags: string[];
  sets_tags: string[];
}

export interface CommandsPushRequest {
  commands?: unknown;
}

export interface CommandsPushResponse {
  count: number;
  ok: boolean;
}

export interface ControlSignalRequest {
  signal: string;
}

export interface ControlSignalResponse {
  ok: boolean;
}

export interface DispatchRequest {
  action: unknown;
}

export interface DispatchResponse {
  control_message?: unknown;
  message?: unknown;
  status: string;
}

export interface EventsAppendRequest {
  data?: unknown;
  event_type: string;
  session_id?: string;
}

export interface EventsAppendResponse {
  ok: boolean;
}

export interface EventsEmitRequest {
  correlation_id?: unknown;
  data?: unknown;
  event_type: string;
}

export interface EventsEmitResponse {
  ok: boolean;
}

export interface HUDCreateChannelRequest {
  accepts_input?: boolean;
  anchor?: unknown;
  channel: string;
  description?: string;
  follows_focus?: boolean;
  min_height?: number;
  width?: number;
}

export interface HUDCreateChannelResponse {
  ok: boolean;
}

export interface HUDHideRequest {
  channel: string;
}

export interface HUDHideResponse {
  ok: boolean;
}

export interface HUDPushRequest {
  channel: string;
  fragments: unknown;
}

export interface HUDPushResponse {
  ok: boolean;
}

export interface HUDRemoveChannelRequest {
  channel: string;
}

export interface HUDRemoveChannelResponse {
  ok: boolean;
  removed: boolean;
}

export interface HUDSetSizeRequest {
  channel: string;
  height: number;
}

export interface HUDSetSizeResponse {
  ok: boolean;
}

export interface HUDShowRequest {
  channel: string;
}

export interface HUDShowResponse {
  ok: boolean;
}

export interface InputClickRequest {
  button?: string;
}

export interface InputClickResponse {
  ok: boolean;
}

export interface InputClipboardActionRequest {
  action: string;
  text?: unknown;
}

export interface InputClipboardActionResponse {
  ok: boolean;
}

export interface InputClipboardReadRequest {
  content_type: string;
}

export interface InputClipboardReadResponse {
  available_types: string[];
  content_type: string;
  file_urls?: unknown;
  image_base64?: unknown;
  text?: unknown;
}

export interface InputClipboardReadAllResponse {
  items: ClipboardContents[];
}

export interface InputClipboardWriteRequest {
  content_type: string;
  data: string;
}

export interface InputClipboardWriteResponse {
  ok: boolean;
}

export interface InputClipboardWriteItemsRequest {
  items?: ClipboardWriteItem[];
}

export interface InputClipboardWriteItemsResponse {
  ok: boolean;
}

export interface InputDoubleClickRequest {
  x?: unknown;
  y?: unknown;
}

export interface InputDoubleClickResponse {
  ok: boolean;
}

export interface InputDragRequest {
  duration_ms?: number;
  from_x: number;
  from_y: number;
  to_x: number;
  to_y: number;
}

export interface InputDragResponse {
  ok: boolean;
}

export interface InputListInputSourcesResponse {
  sources: InputSource[];
}

export interface InputMouseButtonRequest {
  button?: string;
  direction: string;
}

export interface InputMouseButtonResponse {
  ok: boolean;
}

export interface InputPressKeyRequest {
  code?: unknown;
  modifiers?: string[];
  name?: unknown;
}

export interface InputPressKeyResponse {
  ok: boolean;
}

export interface InputRawKeyRequest {
  code: number;
  direction: string;
}

export interface InputRawKeyResponse {
  ok: boolean;
}

export interface InputRightClickRequest {
  x?: unknown;
  y?: unknown;
}

export interface InputRightClickResponse {
  ok: boolean;
}

export interface InputScrollRequest {
  amount?: number;
  direction: string;
}

export interface InputScrollResponse {
  ok: boolean;
}

export interface InputSwitchInputSourceRequest {
  source_id: string;
}

export interface InputSwitchInputSourceResponse {
  result: boolean;
}

export interface InputTypeTextRequest {
  text: string;
}

export interface InputTypeTextResponse {
  ok: boolean;
}

export interface KeyNamesSetRequest {
  names?: Record<string, number>;
}

export interface KeyNamesSetResponse {
  count: number;
  ok: boolean;
}

export interface KeybindsRegisterRequest {
  snapshot: unknown;
}

export interface KeybindsRegisterResponse {
  count: number;
  ok: boolean;
}

export interface MatchAliasesGetResponse {
  aliases: Record<string, string>;
}

export interface MatchAliasesSetRequest {
  aliases?: Record<string, string>;
}

export interface MatchAliasesSetResponse {
  count: number;
  ok: boolean;
}

export interface NativeActivateAppRequest {
  all_windows?: boolean;
  bundle_id: string;
}

export interface NativeActivateAppResponse {
  ok: boolean;
}

export interface NativeActiveSpaceResponse {
  active: ActiveSpace[];
}

export interface NativeAppIconRequest {
  bundle_id: string;
  size?: number;
}

export interface NativeAppIconResponse {
  format: string;
  image_base64: string;
}

export interface NativeAudioDevicesResponse {
  devices: AudioDevice[];
}

export interface NativeAxElementAtPointRequest {
  pid: number;
  x: number;
  y: number;
}

export interface NativeAxElementAtPointResponse {
  actions: string[];
  attributes: string[];
  children_count: number;
  description?: unknown;
  enabled: boolean;
  focused: boolean;
  path: AXPathSegment[];
  position?: unknown;
  role: string;
  size?: unknown;
  subrole?: unknown;
  title?: unknown;
  value?: unknown;
}

export interface NativeAxElementTreeRequest {
  depth?: number;
  element: AXElementRef;
}

export interface NativeAxObserveRequest {
  notifications?: string[];
  pid: number;
}

export interface NativeAxObserveResponse {
  subscription_id: string;
}

export interface NativeAxPerformActionRequest {
  action: string;
  element: AXElementRef;
}

export interface NativeAxPerformActionResponse {
  result: boolean;
}

export interface NativeAxReadAttributesRequest {
  attributes?: string[];
  element: AXElementRef;
}

export interface NativeAxSetAttributeRequest {
  attribute: string;
  element: AXElementRef;
  value: unknown;
}

export interface NativeAxSetAttributeResponse {
  result: boolean;
}

export interface NativeAxUnobserveRequest {
  subscription_id: string;
}

export interface NativeAxUnobserveResponse {
  result: boolean;
}

export interface NativeBatchIsTileableRequest {
  window_ids?: string[];
}

export interface NativeBatchIsTileableResponse {
  results: TileableEntry[];
}

export interface NativeBatchSetFramesRequest {
  frames?: WindowFrame[];
  readback?: boolean;
}

export interface NativeBatchSetFramesResponse {
  results: WindowFrame[];
}

export interface NativeBatteryResponse {
  is_charging: boolean;
  is_plugged_in: boolean;
  is_present: boolean;
  level: number;
  time_remaining_minutes?: unknown;
}

export interface NativeBluetoothDevicesResponse {
  devices: BluetoothDevice[];
}

export interface NativeBordersResponse {
  ok: boolean;
}

export interface NativeBrightnessRequest {
  display_id?: unknown;
}

export interface NativeBrightnessResponse {
  brightness: number;
}

export interface NativeCaptureWindowRequest {
  window_id: string;
}

export interface NativeCaptureWindowResponse {
  format: string;
  image_base64: string;
}

export interface NativeClickMenuItemRequest {
  path?: string[];
  pid: number;
}

export interface NativeClickMenuItemResponse {
  result: boolean;
}

export interface NativeClipboardChangeCountResponse {
  count: number;
}

export interface NativeCloseWindowRequest {
  window_id: string;
}

export interface NativeCloseWindowResponse {
  ok: boolean;
}

export interface NativeColorAtPointRequest {
  x: number;
  y: number;
}

export interface NativeColorAtPointResponse {
  a: number;
  b: number;
  g: number;
  hex: string;
  r: number;
}

export interface NativeCurrentUserResponse {
  full_name: string;
  home_directory: string;
  username: string;
}

export interface NativeCursorResponse {
  x: number;
  y: number;
}

export interface NativeCursorInfoResponse {
  cursor_type: string;
  x: number;
  y: number;
}

export interface NativeDarkModeResponse {
  is_dark: boolean;
}

export interface NativeDefaultBrowserResponse {
  bundle_id: string;
}

export interface NativeDismissNotificationRequest {
  id: string;
}

export interface NativeDismissNotificationResponse {
  ok: boolean;
}

export interface NativeDisplaysResponse {
  displays: DisplayMetadata[];
}

export interface NativeDndResponse {
  enabled: boolean;
  focus_name?: unknown;
}

export interface NativeFileTagsRequest {
  path: string;
  tags?: unknown;
}

export interface NativeForceQuitAppRequest {
  bundle_id: string;
}

export interface NativeForceQuitAppResponse {
  result: boolean;
}

export interface NativeFrontmostAppResponse {
  app?: unknown;
}

export interface NativeGetWindowInfoRequest {
  window_id: string;
}

export interface NativeGetWindowInfoResponse {
  alpha?: unknown;
  bounds: WindowBounds;
  display_id: number;
  is_focused: boolean;
  is_fullscreen: boolean;
  is_minimized: boolean;
  subrole?: unknown;
  title?: unknown;
  window_id: string;
}

export interface NativeHideAppRequest {
  bundle_id: string;
}

export interface NativeHideAppResponse {
  ok: boolean;
}

export interface NativeInstalledAppsResponse {
  apps: InstalledApp[];
}

export interface NativeIsAppHiddenRequest {
  bundle_id: string;
}

export interface NativeIsAppHiddenResponse {
  result: boolean;
}

export interface NativeKeyboardLayoutResponse {
  layout_id: string;
  layout_name: string;
  mappings: Record<string, string>;
}

export interface NativeLaunchAppRequest {
  bundle_id: string;
  new_instance?: boolean;
}

export interface NativeLaunchAppResponse {
  ok: boolean;
}

export interface NativeListNotificationsResponse {
  notifications: DeliveredNotification[];
}

export interface NativeListSpacesResponse {
  spaces: SpaceInfo[];
}

export interface NativeLoginItemsResponse {
  items: LoginItem[];
}

export interface NativeMenuBarRequest {
  pid: number;
}

export interface NativeMenuBarResponse {
  items: MenuItem[];
}

export interface NativeMinimizeWindowRequest {
  window_id: string;
}

export interface NativeMinimizeWindowResponse {
  ok: boolean;
}

export interface NativeMoveWindowToDisplayRequest {
  display_id: number;
  window_id: string;
}

export interface NativeMoveWindowToDisplayResponse {
  ok: boolean;
}

export interface NativeMoveWindowToSpaceRequest {
  space_id: number;
  window_id: string;
}

export interface NativeMoveWindowToSpaceResponse {
  result: boolean;
}

export interface NativeMuteRequest {
  muted: boolean;
}

export interface NativeMuteResponse {
  ok: boolean;
}

export interface NativeNotifyRequest {
  body?: unknown;
  sound?: unknown;
  subtitle?: unknown;
  title: string;
}

export interface NativeNotifyResponse {
  id?: unknown;
}

export interface NativeObserveWindowsRequest {
  pid: number;
}

export interface NativeObserveWindowsResponse {
  subscription_id: string;
}

export interface NativeOpenTargetRequest {
  target: string;
}

export interface NativeOpenTargetResponse {
  ok: boolean;
}

export interface NativePlaySoundRequest {
  name: string;
}

export interface NativePlaySoundResponse {
  ok: boolean;
}

export interface NativePollBurstResponse {
  ok: boolean;
}

export interface NativePreventSleepRequest {
  assertion_id?: unknown;
  reason?: string;
}

export interface NativePreventSleepResponse {
  assertion_id: string;
}

export interface NativeQuickLookRequest {
  path: string;
  size?: number;
}

export interface NativeQuickLookResponse {
  format: string;
  image_base64: string;
}

export interface NativeQuitAppRequest {
  bundle_id: string;
}

export interface NativeQuitAppResponse {
  result: boolean;
}

export interface NativeRaiseWindowRequest {
  window_id: string;
}

export interface NativeRaiseWindowResponse {
  ok: boolean;
}

export interface NativeRevealInFinderRequest {
  path: string;
}

export interface NativeRevealInFinderResponse {
  ok: boolean;
}

export interface NativeRunApplescriptRequest {
  script: string;
}

export interface NativeRunApplescriptResponse {
  exit_code: number;
  stderr: string;
  stdout: string;
}

export interface NativeRunningAppsResponse {
  apps: RunningApp[];
}

export interface NativeScreenLockResponse {
  ok: boolean;
}

export interface NativeScreenshotRequest {
  display_id?: unknown;
  region?: unknown;
  window_id?: unknown;
}

export interface NativeScreenshotResponse {
  format: string;
  image_base64: string;
}

export interface NativeSelectedFinderItemsResponse {
  paths: string[];
}

export interface NativeSetAudioDeviceRequest {
  device_type: string;
  uid: string;
}

export interface NativeSetAudioDeviceResponse {
  ok: boolean;
}

export interface NativeSetBrightnessRequest {
  brightness: number;
  display_id?: unknown;
}

export interface NativeSetBrightnessResponse {
  ok: boolean;
}

export interface NativeSetDarkModeRequest {
  dark: boolean;
}

export interface NativeSetDarkModeResponse {
  ok: boolean;
}

export interface NativeSetDndRequest {
  enabled: boolean;
}

export interface NativeSetDndResponse {
  ok: boolean;
}

export interface NativeSetVolumeRequest {
  volume: number;
}

export interface NativeSetVolumeResponse {
  ok: boolean;
}

export interface NativeSetWindowAlphaRequest {
  alpha: number;
  window_id: string;
}

export interface NativeSetWindowAlphaResponse {
  ok: boolean;
}

export interface NativeSetWindowLevelRequest {
  level: string;
  window_id: string;
}

export interface NativeSetWindowLevelResponse {
  result: boolean;
}

export interface NativeSpeakRequest {
  rate?: unknown;
  text: string;
  voice?: unknown;
}

export interface NativeSpeakResponse {
  ok: boolean;
}

export interface NativeSpotlightRequest {
  limit?: number;
  query: string;
  scope?: unknown;
}

export interface NativeSpotlightResponse {
  results: SpotlightResult[];
}

export interface NativeSystemUptimeResponse {
  formatted: string;
  uptime_seconds: number;
}

export interface NativeToggleFullscreenRequest {
  window_id: string;
}

export interface NativeToggleFullscreenResponse {
  ok: boolean;
}

export interface NativeTrashRequest {
  path: string;
}

export interface NativeTrashResponse {
  result: boolean;
}

export interface NativeUnhideAppRequest {
  bundle_id: string;
}

export interface NativeUnhideAppResponse {
  ok: boolean;
}

export interface NativeUnminimizeWindowRequest {
  window_id: string;
}

export interface NativeUnminimizeWindowResponse {
  ok: boolean;
}

export interface NativeUnobserveWindowsRequest {
  subscription_id: string;
}

export interface NativeUnobserveWindowsResponse {
  result: boolean;
}

export interface NativeVolumeResponse {
  is_muted: boolean;
  volume: number;
}

export interface NativeWarpCursorRequest {
  x: number;
  y: number;
}

export interface NativeWarpCursorResponse {
  ok: boolean;
}

export interface NativeWifiResponse {
  bssid?: unknown;
  is_connected: boolean;
  is_enabled: boolean;
  rssi?: unknown;
  ssid?: unknown;
}

export interface NativeWorldModelRequest {
  on_screen?: boolean;
}

export interface SelectionPickRequest {
  index: number;
}

export interface SelectionPickResponse {
  control_message: string;
  item_id: string;
  ok: boolean;
  reset_engine: boolean;
}

export interface SelectionSetRequest {
  channel?: unknown;
  items?: unknown;
  title?: unknown;
}

export interface SelectionSetResponse {
  ok: boolean;
}

export interface SessionEndCleanupResponse {
  control_message?: unknown;
  ok: boolean;
  reset_engine: boolean;
}

export interface SettingsRulesCreateRequest {
  newruleactionjson?: unknown;
  newruleactiontype?: unknown;
  newruleactionval?: unknown;
  newrulecategory?: unknown;
  newruleclearstags?: unknown;
  newruledescription?: unknown;
  newrulephrase?: unknown;
  newrulerequirestags?: unknown;
  newrulesetstags?: unknown;
}

export interface SettingsRulesCreateResponse {
  ok: boolean;
}

export interface SettingsRulesUpdateRequest {
  canonical: string;
  newruleactionjson?: unknown;
  newruleactiontype?: unknown;
  newruleactionval?: unknown;
  newrulecategory?: unknown;
  newruleclearstags?: unknown;
  newruledescription?: unknown;
  newrulephrase?: unknown;
  newrulerequirestags?: unknown;
  newrulesetstags?: unknown;
}

export interface SettingsRulesUpdateResponse {
  ok: boolean;
}

export interface SystemLaunchAppRequest {
  bundle_id: string;
  new_instance?: boolean;
}

export interface SystemLaunchAppResponse {
  ok: boolean;
}

export interface SystemNotifyRequest {
  body: string;
  duration_secs?: unknown;
  title: string;
}

export interface SystemNotifyResponse {
  ok: boolean;
}

export interface SystemRunShellRequest {
  command: string;
}

export interface SystemRunShellResponse {
  ok: boolean;
}

export interface TagsGetResponse {
  tags: string[];
}

export interface TagsModifyRequest {
  clear?: string[];
  clear_scoped?: boolean;
  set?: string[];
}

export interface TagsModifyResponse {
  tags: string[];
}

// ===== Actuator → Plugin request/response types =====

export interface OnActionRequest {
  action: string;
  active_app?: string;
  active_window_id?: string;
  params?: unknown;
}

export interface OnActionResponse {
  control_message?: string;
  status: OnActionStatus;
}

export interface OnChannelActionRequest {
  action: string;
  channel: string;
  payload?: unknown;
}

export interface OnChannelActionResponse {
  close_channel?: boolean;
  control_message?: string;
  status: OnActionStatus;
}

export interface OnCommandsChangedRequest {
  commands_by_plugin: unknown;
  user_commands?: unknown[];
}

export interface OnCommandsChangedResponse {
  processed_count: number;
}

export interface RenderHUDRequest {
  footer?: string;
  hud_mode: string;
  sections?: HudSection[];
  title?: string;
}

export interface RenderSettingsRequest {
  active_tags?: string[];
  commands?: unknown;
  search?: string;
  tab_key: string;
}

export interface RenderSettingsResponse {
  html: string;
}

export interface SpeechPipelineFullRequest {
  channel_visibility?: Record<string, boolean>;
  is_continuous?: boolean;
  is_final: boolean;
  mute_matching?: boolean;
  scoped_prefixes?: string[];
  segments: IngestSegmentSpec[];
  selection_active?: boolean;
  selection_items?: SelectionItemSpec[];
  session_end: boolean;
  session_id?: unknown;
  should_lift?: boolean;
  tags?: string[];
}

export interface SpeechPipelineFullResponse {
  control_message?: unknown;
  paste_text?: unknown;
  reset_engine?: boolean;
  status?: string;
}
