// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

// ===== Shared types (from components/schemas) =====

export interface AXElementInfo {
  actions: string[];
  attributes: string[];
  children_count: number;
  description?: string;
  enabled: boolean;
  focused: boolean;
  path: AXPathSegment[];
  position?: unknown;
  role: string;
  size?: unknown;
  subrole?: string;
  title?: string;
  value?: unknown;
}

export interface AXElementNode {
  children: AXElementNode[];
  element: AXElementInfo;
}

export interface AXElementRef {
  path: AXPathSegment[];
  pid: number;
}

export interface AXPathSegment {
  index: number;
  role: string;
}

export interface ActionFieldSchema {
  display?: unknown;
  enum_values: string[];
  field_type: FieldType;
  fields: ActionFieldSchema[];
  key: string;
  label: string;
  placeholder?: string;
  required: boolean;
}

export interface ActionTypeSchema {
  fields: ActionFieldSchema[];
  label: string;
  modes: string[];
}

export interface ActiveSpace {
  display_id: number;
  space_id: number;
}

export interface AudioDevice {
  id: number;
  is_default_input: boolean;
  is_default_output: boolean;
  is_input: boolean;
  is_output: boolean;
  name: string;
  uid: string;
}

export interface BarcodeResult {
  height: number;
  payload: string;
  symbology: string;
  width: number;
  x: number;
  y: number;
}

export interface BleCharacteristic {
  properties: string[];
  uuid: string;
}

export interface BleService {
  characteristics: BleCharacteristic[];
  uuid: string;
}

export interface BleWriteEntry {
  characteristic_uuid: string;
  data: number[];
  service_uuid: string;
  write_type: string;
}

export interface BluetoothDevice {
  address: string;
  device_type?: string;
  is_connected: boolean;
  is_paired: boolean;
  name: string;
}

export interface CalendarEvent {
  calendar?: string;
  end?: string;
  is_all_day: boolean;
  location?: string;
  start?: string;
  title: string;
}

export interface CameraDevice {
  is_connected: boolean;
  model_id: string;
  name: string;
  unique_id: string;
}

export interface CaptureManifestRow {
  file: string;
  text: string;
  ts: string;
}

export interface ClipboardContents {
  available_types: string[];
  content_type: string;
  file_urls?: unknown;
  image_base64?: string;
  text?: string;
}

export interface ClipboardWriteItem {
  content_type: string;
  file_urls?: unknown;
  image_base64?: string;
  text?: string;
}

export interface CollectionPutEntry {
  id: string;
  payload?: unknown;
}

export interface CollectionRecord {
  id: string;
  payload?: unknown;
  revision: number;
  timestamp_ms: number;
}

export interface CollectionsListItem {
  id: string;
  source: string;
  subtitle?: string;
  title: string;
}

export interface CollectionsListSection {
  entry_count: number;
  items: CollectionsListItem[];
  label: string;
  name: string;
  plugin: string;
}

export interface CommandOverride {
  action: string;
  default_pattern: string;
  new_pattern: string;
}

export interface CommandRowData {
  action: string;
  action_json?: unknown;
  canonical: string;
  category: string;
  clears_tags: string[];
  description?: string;
  is_user: boolean;
  pattern: string;
  plugin_name: string;
  requires_tags: string[];
  sets_tags: string[];
  tier: string;
  variants: string[];
}

export interface CommandSpec {
  action?: unknown;
  cancels_bridge: boolean;
  category?: string;
  clears_tags: string[];
  description?: string;
  pattern: unknown[];
  requires_tags: string[];
  sets_on_partial: string[];
  sets_tags: string[];
  variants: unknown[];
}

export interface ContactInfo {
  email?: string;
  name: string;
  organization?: string;
  phone?: string;
}

export interface CpuInfo {
  architecture: string;
  chip: string;
  core_count: number;
  efficiency_cores?: number;
  performance_cores?: number;
}

export interface DeliveredNotification {
  body?: string;
  delivered_at: string;
  id: string;
  title: string;
}

export interface DirectoryEntry {
  is_dir: boolean;
  is_symlink: boolean;
  name: string;
  path: string;
  size: number;
}

export interface DiscoverItem {
  id: string;
  subtitle?: string;
  tag: string;
  title: string;
}

export interface DisplayColorProfile {
  color_space: string;
  display_id: number;
  profile_name: string;
}

export interface DisplayInfo {
  h: number;
  id: number;
  visible_h: number;
  visible_w: number;
  visible_x: number;
  visible_y: number;
  w: number;
  x: number;
  y: number;
}

export interface DisplayMetadata {
  display_id: number;
  h: number;
  is_builtin: boolean;
  is_primary: boolean;
  name: string;
  refresh_rate: number;
  resolution_h: number;
  resolution_w: number;
  scale_factor: number;
  visible_h: number;
  visible_w: number;
  visible_x: number;
  visible_y: number;
  w: number;
  x: number;
  y: number;
}

export interface DisplayRotation {
  degrees: number;
  display_id: number;
}

export interface EnumeratedCommand {
  action: string;
  category?: string;
  description?: string;
  dynamic: boolean;
  dynamic_owner?: string;
  id: string;
  owner_plugin: string;
  pattern: string;
  requires_tags: string[];
  sets_tags: string[];
}

export interface ExternalDisk {
  file_system?: string;
  free_bytes: number;
  is_removable: boolean;
  mount_point: string;
  name: string;
  total_bytes: number;
}

/**
 * Where a field appears in generic UI rendering. Each field on a
 * collection declares at most one role; surfaces (discovery HUD,
 * settings UI, etc.) interpret roles on their own terms.
 * 
 * See `notes/DESIGN_COLLECTION_FIELD_ROLES.md` for the full vocabulary
 * rationale. Roles `primary`, `secondary`, `description`, `payload` are
 * consumed by `services::matching_service::expand_collections_to_items`
 * for discovery items; `summary` is consumed by the settings UI's
 * log-kind timeline rows.
 */
export type FieldDisplay = "primary" | "secondary" | "description" | "payload" | "summary";

/**
 * The declared shape of a single action-type field. See `ActionFieldSchema`.
 * 
 * Wire format uses snake_case strings (`"string"`, `"int"`, `"enum"`, …).
 * Unknown values fail deserialization — that's deliberate: a typo in
 * `plugin.json` should surface at load time, not at dispatch. The `Json`
 * variant is the documented escape hatch for shapes too dynamic to
 * declare statically.
 */
export type FieldType = "string" | "int" | "number" | "boolean" | "string[]" | "enum" | "object" | "json";

export interface Frame {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface HidDeviceEntry {
  axes: number;
  ble_uuid?: string;
  buttons: number;
  id: string;
  product: string;
  product_id: number;
  seized: boolean;
  transport: string;
  vendor_id: number;
}

export interface HidElementEntry {
  bit_offset: number;
  byte_offset: number;
  logical_max: number;
  logical_min: number;
  report_count: number;
  report_id: number;
  report_size: number;
  type: string;
  usage: number;
  usage_page: number;
}

export interface HudItem {
  icon?: string;
  id: string;
  subtitle?: string;
  tag?: string;
  title: string;
}

export interface HudResponse {
  content_html?: string;
  footer: string;
  sections?: HudSection[];
  title: string;
}

export interface HudSection {
  items: HudItem[];
  title: string;
}

export interface InputSource {
  id: string;
  is_active: boolean;
  name: string;
}

export interface InstalledApp {
  bundle_id: string;
  name: string;
}

export interface ListCommandItem {
  dynamic: boolean;
  dynamic_owner?: string;
  id: string;
  subtitle?: string;
  tag?: string;
  title: string;
}

export interface ListCommandSection {
  items: ListCommandItem[];
  title: string;
}

export interface ListOpts {
  cursor?: string;
  limit?: number;
  since_ms?: number;
  until_ms?: number;
}

export interface ListeningPort {
  pid?: number;
  port: number;
  process_name?: string;
  protocol: string;
}

export interface LogEntry {
  id: string;
  payload?: unknown;
  timestamp_ms: number;
}

export interface LoginItem {
  bundle_id?: string;
  hidden: boolean;
  name: string;
  path: string;
}

/**
 * Which category the matcher's tiebreaker chose. Mirrors the four
 * branches of `find_match_at_start_with_telemetry`: gated Completes win over
 * ungated Completes (scoped beats unscoped within the gated set), an
 * ungated Complete loses if any gated command had a Partial in flight
 * (`suppress_ungated`), and `NoMatch` is the fall-through.
 */
export type MatchWinner = "gated_scoped" | "gated_unscoped" | "ungated" | "no_match";

export interface MemoryInfo {
  available_bytes: number;
  swap_total_bytes: number;
  swap_used_bytes: number;
  total_bytes: number;
  used_bytes: number;
}

export interface MenuItem {
  children: MenuItem[];
  enabled: boolean;
  index: number;
  shortcut?: string;
  title: string;
}

/**
 * How contributions to a shared store are merged when read.
 * 
 * `Keyed` was removed in Phase 3d of the collection-primitive
 * unification — it had no legitimate multi-contributor users in
 * practice; the implicit `Preset::Data` default flipped to
 * `Authoritative` (matches the dominant single-writer pattern).
 * `Collect` remains for genuine multi-contributor pooling (keybinds,
 * `Preset::Tag` multi-cardinality tag collections).
 */
export type MergeStrategy = "authoritative" | "collect";

export interface NetworkInterface {
  display_name: string;
  ipv4?: string;
  ipv6?: string;
  is_loopback: boolean;
  is_up: boolean;
  mac_address?: string;
  name: string;
}

export interface NowPlayingInfo {
  album?: string;
  app_bundle_id?: string;
  artist?: string;
  duration?: number;
  elapsed?: number;
  is_playing: boolean;
  title?: string;
}

export interface OcrRegion {
  confidence: number;
  height: number;
  text: string;
  width: number;
  x: number;
  y: number;
}

export type OnActionStatus = "ok" | "error" | "not_handled";

/**
 * What a HUD window does when the pointer moves into its frame.
 */
export type OnPointer = "none" | "fade";

export interface PipelineStatusEntry {
  ephemeral: boolean;
  name: string;
}

export interface PipelineTranscriptAlternative {
  confidence: number;
  text: string;
}

export type PluginLogLevel = "trace" | "info" | "warn" | "error" | "debug";

export interface PoolStageStatusEntry {
  alive: boolean;
  generation: number;
  leased: boolean;
  name: string;
}

export interface PrinterInfo {
  is_default: boolean;
  name: string;
  state: string;
}

export interface ProbeItem {
  apply_bias: boolean;
  audio: string;
  bias_strength?: number;
  id: string;
  noise?: unknown;
  words: string[];
}

export interface ProbeLine {
  error: string;
  id: string;
  text: string;
}

export interface ProbeNoise {
  seed: number;
  snr_db: number;
}

export interface ProcessInfo {
  cpu_percent?: number;
  memory_bytes?: number;
  name: string;
  path?: string;
  pid: number;
  user?: string;
}

export interface RecordingRow {
  disposition: string;
  engine: string;
  file: string;
  heard: string;
  matched: boolean;
  target: string;
  ts: string;
}

export interface ReminderItem {
  due_date?: string;
  is_completed: boolean;
  list_name?: string;
  priority: number;
  title: string;
}

export interface ResolveTelemetry {
  gated_partial_seen: boolean;
  winner: MatchWinner;
  winning_pattern?: string;
}

export interface RunningApp {
  bundle_id?: string;
  is_active: boolean;
  is_hidden: boolean;
  name: string;
  pid: number;
}

export interface ScreenshotRegion {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface SettingsListSchemaInfo {
  description: string;
  entry_count: number;
  label: string;
  source_plugin: string;
}

export interface SettingsTagSchemaInfo {
  description: string;
  label: string;
  source_plugin: string;
}

export interface ShortcutInfo {
  folder?: string;
  name: string;
}

export interface SpaceInfo {
  display_id: number;
  is_active: boolean;
  space_id: number;
  space_type: string;
}

export interface SpeechLocale {
  identifier: string;
  is_available: boolean;
  language: string;
}

export interface SpotlightResult {
  kind: string;
  modified: string;
  name: string;
  path: string;
  size?: number;
}

export interface SystemAppearance {
  accent_color?: string;
  highlight_color?: string;
  increase_contrast: boolean;
  reduce_motion: boolean;
  reduce_transparency: boolean;
}

export interface TiedCandidate {
  action?: unknown;
  args: Record<string, unknown>;
  clears_tags: string[];
  consumed_count: number;
  label: string;
  owner_plugin: string;
  requires_tags: string[];
  sets_tags: string[];
}

export interface TileableEntry {
  tileable: boolean;
  window_id: string;
}

export interface TtsVoice {
  identifier: string;
  language: string;
  name: string;
  quality: string;
}

export interface UsbDevice {
  manufacturer?: string;
  name: string;
  product_id?: string;
  serial_number?: string;
  vendor_id?: string;
}

export interface WindowBounds {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface WindowDetail {
  alpha?: number;
  bounds: WindowBounds;
  display_id: number;
  is_focused: boolean;
  is_fullscreen: boolean;
  is_minimized: boolean;
  subrole?: string;
  title?: string;
  window_id: string;
}

export interface WindowFrame {
  h: number;
  w: number;
  window_id: string;
  x: number;
  y: number;
}

export interface WindowInfo {
  app_id: string;
  app_name: string;
  h: number;
  id: string;
  source: string;
  title: string;
  w: number;
  x: number;
  y: number;
}

export interface WorldModel {
  active_app?: string;
  active_window_id?: string;
  displays: DisplayInfo[];
  keyboard_layout_id: string;
  windows: WindowInfo[];
}

// ===== Plugin → Actuator request/response types =====

export interface ActionsListResponse {
  actions: Record<string, ActionTypeSchema>;
}

export interface CalibrationApplyRequest {
  command_id: string;
  trial_id: string;
}

export interface CalibrationApplyResponse {
  fixture_handle: string;
  kind: string;
  tags: string[];
}

export interface CalibrationBiasApplyRequest {
  force?: boolean;
  strength: number;
}

export interface CalibrationBiasApplyResponse {
  applied: boolean;
  previous_provenance: string;
}

export interface CalibrationCaptureProbeRequest {
  items: ProbeItem[];
  max_active?: number;
  model: string;
  stage: string;
}

export interface CalibrationCaptureProbeResponse {
  lines: ProbeLine[];
  model_version?: string;
}

export interface CalibrationCaptureReadCorpusResponse {
  rows: RecordingRow[];
}

export interface CalibrationCaptureReadManifestRequest {
  game: string;
}

export interface CalibrationCaptureReadManifestResponse {
  lines: CaptureManifestRow[];
}

export interface CalibrationCaptureWriteCorpusRequest {
  mode: string;
  rows: RecordingRow[];
}

export interface CalibrationCaptureWriteCorpusResponse {
  total: number;
}

export interface CalibrationRecordingsClearResponse {
  removed: number;
}

export interface CalibrationRecordingsDeleteRequest {
  file: string;
}

export interface CalibrationRecordingsDeleteResponse {
  deleted: boolean;
}

export interface CalibrationRecordingsExportRequest {
  confirmed_only?: boolean;
}

export interface CalibrationRecordingsExportResponse {
  count: number;
  path: string;
}

export interface CalibrationRecordingsListRequest {
  limit?: number;
}

export interface CalibrationRecordingsListResponse {
  recordings: RecordingRow[];
  total: number;
}

export interface CalibrationRecordingsSetDispositionRequest {
  disposition: string;
  file: string;
}

export interface CalibrationRecordingsSetDispositionResponse {
  ok: boolean;
}

export interface CalibrationRecordingsSweepRequest {
  game?: string;
}

export interface CalibrationRecordingsSweepResponse {
  removed: number;
}

export interface CalibrationRegisterFixtureHandleRequest {
  fixture_handle: string;
  owner_plugin_id: string;
  trial_id: string;
}

export interface CalibrationResolveSamplesRequest {
  command_id: string;
}

export interface CalibrationResolveSamplesResponse {
  prompts: string[];
}

export interface CalibrationTrialBeginResponse {
  trial_id: string;
}

export interface CalibrationTrialEndRequest {
  trial_id: string;
}

export interface CalibrationTrialEndResponse {
  released_handle_count: number;
}

export interface CollectionAppendRequest {
  name: string;
  payload: unknown;
}

export interface CollectionAppendResponse {
  entry: LogEntry;
}

export interface CollectionCountRequest {
  name: string;
}

export interface CollectionCountResponse {
  count: number;
}

export interface CollectionDeleteRecordsRequest {
  ids?: string[];
  name: string;
}

export interface CollectionDeleteRecordsResponse {
  already_absent: number;
  deleted: number;
}

export interface CollectionFetchRequest {
  id: string;
  name: string;
}

export interface CollectionFetchResponse {
  record?: unknown;
}

export interface CollectionGetRequest {
  name: string;
}

export interface CollectionGetResponse {
  data: unknown;
  entries?: unknown;
  introducer: string;
  merge: MergeStrategy;
  name: string;
}

export interface CollectionListRequest {
  name: string;
  opts?: ListOpts;
}

export interface CollectionListResponse {
  records: CollectionRecord[];
  total: number;
}

export interface CollectionPatchRequest {
  fields: unknown;
  id: string;
  name: string;
}

export interface CollectionPatchResponse {
  ok: boolean;
}

export interface CollectionPutRequest {
  entries?: CollectionPutEntry[];
  label?: string;
  name: string;
  roles?: unknown;
}

export interface CollectionPutResponse {
  count: number;
  ok: boolean;
}

export interface CollectionsListRequest {
  kind?: string;
}

export interface CollectionsListResponse {
  sections: CollectionsListSection[];
}

export interface CommandsAddAliasRequest {
  action: string;
  default_pattern: string;
  new_pattern: string;
}

export interface CommandsAddAliasResponse {
  ok: boolean;
}

export interface CommandsDeleteRequest {
  canonical: string;
}

export interface CommandsDeleteResponse {
  ok: boolean;
}

export interface CommandsEnumerateResponse {
  commands: EnumeratedCommand[];
}

export interface CommandsListResponse {
  footer: string;
  sections: ListCommandSection[];
  title: string;
}

export interface CommandsListAliasesResponse {
  aliases: CommandOverride[];
}

export interface CommandsListOverridesResponse {
  overrides: CommandOverride[];
}

export interface CommandsPushRequest {
  commands?: unknown;
}

export interface CommandsPushResponse {
  count: number;
  ok: boolean;
}

export interface CommandsRemoveAliasRequest {
  action: string;
  default_pattern: string;
  new_pattern: string;
}

export interface CommandsRemoveAliasResponse {
  ok: boolean;
  removed: boolean;
}

export interface CommandsResetRequest {
  canonical: string;
}

export interface CommandsResetResponse {
  ok: boolean;
}

export interface CommandsResetOverrideRequest {
  action: string;
  default_pattern: string;
}

export interface CommandsResetOverrideResponse {
  ok: boolean;
  removed: boolean;
}

export interface CommandsResolveRequest {
  active_tags?: unknown;
  collections?: unknown;
  prefer_owner?: string;
  preview?: boolean;
  require_tag?: string;
  session_id?: string;
  source?: string;
  words?: string[];
}

export interface CommandsResolveResponse {
  action?: unknown;
  active_plugin_gates?: string[];
  args: Record<string, unknown>;
  bridge_active?: boolean;
  clears_tags: string[];
  consumed_count: number;
  has_completions: boolean;
  items: DiscoverItem[];
  matched: boolean;
  next_words: string[];
  owner_plugin?: string;
  requires_tags: string[];
  scoped_prefixes?: string[];
  scoped_tags?: string[];
  sets_tags: string[];
  telemetry: ResolveTelemetry;
  tied_candidates?: TiedCandidate[];
  title: string;
  trace_id?: string;
}

export interface CommandsSetOverrideRequest {
  action: string;
  default_pattern: string;
  new_pattern: string;
}

export interface CommandsSetOverrideResponse {
  ok: boolean;
}

export interface ControlSignalRequest {
  signal: string;
}

export interface ControlSignalResponse {
  ok: boolean;
}

export interface DiscoveryClosedResponse {
  ok: boolean;
}

export interface DispatchRequest {
  action: unknown;
  session_id?: string;
  trace_id?: string;
}

export interface DispatchResponse {
  control_message?: string;
  handler?: string;
  message?: string;
  result?: unknown;
  status: string;
}

export interface EffectsAssertRequest {
  name: string;
}

export interface EffectsAssertResponse {
  already_held: boolean;
  displaced?: string;
  enforced: boolean;
  granted: boolean;
}

export interface EffectsIsActiveRequest {
  name: string;
}

export interface EffectsIsActiveResponse {
  active: boolean;
  current_owner?: string;
}

export interface EffectsRetractRequest {
  name: string;
}

export interface EffectsRetractResponse {
  new_owner?: string;
  retracted: boolean;
}

export interface EventsAppendRequest {
  data?: unknown;
  event_type: string;
  session_id?: string;
}

export interface EventsAppendResponse {
  ok: boolean;
}

export interface EventsEmitRequest {
  correlation_id?: string;
  data?: unknown;
  event_type: string;
}

export interface EventsEmitResponse {
  ok: boolean;
}

export interface HUDCreateChannelRequest {
  accepts_input?: boolean;
  anchor?: unknown;
  channel: string;
  description?: string;
  draggable?: boolean;
  follows_focus?: boolean;
  min_height?: number;
  on_pointer?: OnPointer;
  transparent?: boolean;
  width?: number;
}

export interface HUDCreateChannelResponse {
  ok: boolean;
}

export interface HUDHideRequest {
  channel: string;
}

export interface HUDHideResponse {
  ok: boolean;
}

export interface HUDPushRequest {
  channel: string;
  fragments: unknown;
}

export interface HUDPushResponse {
  ok: boolean;
}

export interface HUDRemoveChannelRequest {
  channel: string;
}

export interface HUDRemoveChannelResponse {
  ok: boolean;
  removed: boolean;
}

export interface HUDSetSizeRequest {
  channel: string;
  height: number;
}

export interface HUDSetSizeResponse {
  ok: boolean;
}

export interface HUDShowRequest {
  channel: string;
}

export interface HUDShowResponse {
  ok: boolean;
}

export interface InputClickRequest {
  button?: string;
}

export interface InputClickResponse {
  ok: boolean;
}

export interface InputClipboardActionRequest {
  action: string;
  text?: string;
}

export interface InputClipboardActionResponse {
  ok: boolean;
}

export interface InputClipboardHistoryResponse {
  entries: string[];
}

export interface InputClipboardReadRequest {
  content_type: string;
}

export interface InputClipboardReadResponse {
  available_types: string[];
  content_type: string;
  file_urls?: unknown;
  image_base64?: string;
  text?: string;
}

export interface InputClipboardReadAllResponse {
  items: ClipboardContents[];
}

export interface InputClipboardReadFormatRequest {
  format: string;
}

export interface InputClipboardReadFormatResponse {
  data: string;
}

export interface InputClipboardWriteRequest {
  content_type: string;
  data: string;
}

export interface InputClipboardWriteResponse {
  ok: boolean;
}

export interface InputClipboardWriteItemsRequest {
  items?: ClipboardWriteItem[];
}

export interface InputClipboardWriteItemsResponse {
  ok: boolean;
}

export interface InputDoubleClickRequest {
  x?: number;
  y?: number;
}

export interface InputDoubleClickResponse {
  ok: boolean;
}

export interface InputDragRequest {
  duration_ms?: number;
  from_x: number;
  from_y: number;
  to_x: number;
  to_y: number;
}

export interface InputDragResponse {
  ok: boolean;
}

export interface InputListInputSourcesResponse {
  sources: InputSource[];
}

export interface InputMouseButtonRequest {
  button?: string;
  direction: string;
}

export interface InputMouseButtonResponse {
  ok: boolean;
}

export interface InputPressKeyRequest {
  code?: number;
  modifiers?: string[];
  name?: string;
}

export interface InputPressKeyResponse {
  ok: boolean;
}

export interface InputRawKeyRequest {
  code: number;
  direction: string;
}

export interface InputRawKeyResponse {
  ok: boolean;
}

export interface InputRightClickRequest {
  x?: number;
  y?: number;
}

export interface InputRightClickResponse {
  ok: boolean;
}

export interface InputScrollRequest {
  amount?: number;
  direction: string;
  unit?: string;
}

export interface InputScrollResponse {
  ok: boolean;
}

export interface InputSelectAllResponse {
  ok: boolean;
}

export interface InputSwitchInputSourceRequest {
  source_id: string;
}

export interface InputSwitchInputSourceResponse {
  result: boolean;
}

export interface InputTripleClickRequest {
  x?: number;
  y?: number;
}

export interface InputTripleClickResponse {
  ok: boolean;
}

export interface InputTypeTextRequest {
  text: string;
}

export interface InputTypeTextResponse {
  ok: boolean;
}

export interface KeyNamesSetRequest {
  names?: Record<string, number>;
}

export interface KeyNamesSetResponse {
  count: number;
  ok: boolean;
}

export interface KeybindsRegisterRequest {
  snapshot: unknown;
}

export interface KeybindsRegisterResponse {
  count: number;
  ok: boolean;
}

export interface ModelDeleteRequest {
  ref: string;
}

export interface ModelDeleteResponse {
  ok: boolean;
}

export interface NativeAccentColorResponse {
  color: string;
}

export interface NativeAccessibilityDisplayInvertResponse {
  inverted: boolean;
}

export interface NativeAccessibilityEnabledResponse {
  enabled: boolean;
}

export interface NativeActivateAppRequest {
  all_windows?: boolean;
  bundle_id: string;
}

export interface NativeActivateAppResponse {
  ok: boolean;
}

export interface NativeActiveNetworkServiceResponse {
  service: string;
}

export interface NativeActivePortsResponse {
  ports: ListeningPort[];
}

export interface NativeActiveSpaceResponse {
  active: ActiveSpace[];
}

export interface NativeAirdropEnabledResponse {
  enabled: boolean;
}

export interface NativeAirportPowerResponse {
  on: boolean;
}

export interface NativeAlertSoundResponse {
  name: string;
}

export interface NativeAllWindowIdsResponse {
  window_ids: string[];
}

export interface NativeApfsSnapshotsResponse {
  value: string;
}

export interface NativeAppBundlePathRequest {
  bundle_id: string;
}

export interface NativeAppBundlePathResponse {
  path: string;
}

export interface NativeAppFocusedWindowIDRequest {
  bundle_id: string;
}

export interface NativeAppIconRequest {
  bundle_id: string;
  size?: number;
}

export interface NativeAppIconResponse {
  format: string;
  image_base64: string;
}

export interface NativeAppIconPathRequest {
  bundle_id: string;
}

export interface NativeAppIsAgentRequest {
  bundle_id: string;
}

export interface NativeAppIsAgentResponse {
  enabled: boolean;
}

export interface NativeAppIsRunningRequest {
  bundle_id: string;
}

export interface NativeAppIsRunningResponse {
  running: boolean;
}

export interface NativeAppLaunchAtLoginRequest {
  bundle_id: string;
}

export interface NativeAppLaunchAtLoginResponse {
  enabled: boolean;
}

export interface NativeAppMetadataRequest {
  bundle_id: string;
}

export interface NativeAppMetadataResponse {
  build?: string;
  bundle_id: string;
  category?: string;
  min_os_version?: string;
  name: string;
  path: string;
  version?: string;
}

export interface NativeAppPathRequest {
  bundle_id: string;
}

export interface NativeAppPidRequest {
  bundle_id: string;
}

export interface NativeAppSupportDirectoryResponse {
  path: string;
}

export interface NativeAppVersionRequest {
  bundle_id: string;
}

export interface NativeAppWindowsRequest {
  bundle_id: string;
}

export interface NativeAppWindowsResponse {
  windows: WindowDetail[];
}

export interface NativeAppWindowsCountRequest {
  bundle_id: string;
}

export interface NativeAudioDeviceVolumeRequest {
  device_uid: string;
}

export interface NativeAudioDeviceVolumeResponse {
  is_muted: boolean;
  volume: number;
}

export interface NativeAudioDevicesResponse {
  devices: AudioDevice[];
}

export interface NativeAudioInputDeviceResponse {
  device: string;
}

export interface NativeAudioOutputDeviceResponse {
  device: string;
}

export interface NativeAutoBrightnessResponse {
  enabled: boolean;
}

export interface NativeAutoRearrangeSpacesResponse {
  enabled: boolean;
}

export interface NativeAutoTimezoneResponse {
  enabled: boolean;
}

export interface NativeAutocorrectEnabledResponse {
  enabled: boolean;
}

export interface NativeAutomaticLoginUserResponse {
  value: string;
}

export interface NativeAutomationPermissionRequest {
  bundle_id: string;
}

export interface NativeAutomationPermissionResponse {
  enabled: boolean;
}

export interface NativeAxElementAtPointRequest {
  pid: number;
  x: number;
  y: number;
}

export interface NativeAxElementAtPointResponse {
  actions: string[];
  attributes: string[];
  children_count: number;
  description?: string;
  enabled: boolean;
  focused: boolean;
  path: AXPathSegment[];
  position?: unknown;
  role: string;
  size?: unknown;
  subrole?: string;
  title?: string;
  value?: unknown;
}

export interface NativeAxElementTreeRequest {
  depth?: number;
  element: AXElementRef;
}

export interface NativeAxObserveRequest {
  notifications?: string[];
  pid: number;
}

export interface NativeAxObserveResponse {
  subscription_id: string;
}

export interface NativeAxPerformActionRequest {
  action: string;
  element: AXElementRef;
}

export interface NativeAxPerformActionResponse {
  result: boolean;
}

export interface NativeAxReadAttributesRequest {
  attributes?: string[];
  element: AXElementRef;
}

export interface NativeAxSetAttributeRequest {
  attribute: string;
  element: AXElementRef;
  value: unknown;
}

export interface NativeAxSetAttributeResponse {
  result: boolean;
}

export interface NativeAxUnobserveRequest {
  subscription_id: string;
}

export interface NativeAxUnobserveResponse {
  result: boolean;
}

export interface NativeBatchIsTileableRequest {
  window_ids?: string[];
}

export interface NativeBatchIsTileableResponse {
  results: TileableEntry[];
}

export interface NativeBatchSetFramesRequest {
  frames?: WindowFrame[];
  readback?: boolean;
}

export interface NativeBatchSetFramesResponse {
  results: WindowFrame[];
}

export interface NativeBatteryResponse {
  is_charging: boolean;
  is_plugged_in: boolean;
  is_present: boolean;
  level: number;
  time_remaining_minutes?: number;
}

export interface NativeBatteryHealthResponse {
  value: string;
}

export interface NativeBleDiscoverServicesRequest {
  device_identifier: string;
}

export interface NativeBleDiscoverServicesResponse {
  services: BleService[];
}

export interface NativeBleSubscribeRequest {
  characteristic_uuid: string;
  device_identifier: string;
  service_uuid: string;
}

export interface NativeBleSubscribeResponse {
  success: boolean;
}

export interface NativeBleSubscribeAllThenWriteRequest {
  device_identifier: string;
  subscribe_services?: string[];
  writes?: BleWriteEntry[];
}

export interface NativeBleSubscribeAllThenWriteResponse {
  success: boolean;
}

export interface NativeBleWriteRequest {
  characteristic_uuid: string;
  data?: number[];
  device_identifier: string;
  service_uuid: string;
  write_type?: string;
}

export interface NativeBleWriteResponse {
  success: boolean;
}

export interface NativeBluetoothDevicesResponse {
  devices: BluetoothDevice[];
}

export interface NativeBluetoothPowerResponse {
  on: boolean;
}

export interface NativeBoldTextEnabledResponse {
  enabled: boolean;
}

export interface NativeBootVolumeResponse {
  name: string;
}

export interface NativeBordersResponse {
  ok: boolean;
}

export interface NativeBrightnessRequest {
  display_id?: number;
}

export interface NativeBrightnessResponse {
  brightness: number;
}

export interface NativeBundleForRemotePortRequest {
  remote_port: number;
}

export interface NativeBundleForRemotePortResponse {
  bundle_id: string;
}

export interface NativeCalendarEventsRangeRequest {
  end: string;
  start: string;
}

export interface NativeCalendarEventsRangeResponse {
  events: CalendarEvent[];
}

export interface NativeCalendarEventsTodayResponse {
  events: CalendarEvent[];
}

export interface NativeCalendarPermissionResponse {
  enabled: boolean;
}

export interface NativeCameraPermissionResponse {
  enabled: boolean;
}

export interface NativeCamerasResponse {
  cameras: CameraDevice[];
}

export interface NativeCapsLockStateResponse {
  on: boolean;
}

export interface NativeCaptureWindowRequest {
  window_id: string;
}

export interface NativeCaptureWindowResponse {
  format: string;
  image_base64: string;
}

export interface NativeCascadeWindowsRequest {
  bundle_id: string;
}

export interface NativeCascadeWindowsResponse {
  ok: boolean;
}

export interface NativeCenterWindowRequest {
  window_id: string;
}

export interface NativeCenterWindowResponse {
  ok: boolean;
}

export interface NativeCheckPermissionRequest {
  permission: string;
}

export interface NativeCheckPermissionResponse {
  permission: string;
  status: string;
}

export interface NativeClearFileQuarantineRequest {
  path: string;
}

export interface NativeClearFileQuarantineResponse {
  ok: boolean;
}

export interface NativeClearNotificationsRequest {
  bundle_id: string;
}

export interface NativeClearNotificationsResponse {
  ok: boolean;
}

export interface NativeClickMenuItemRequest {
  path?: string[];
  pid: number;
}

export interface NativeClickMenuItemResponse {
  result: boolean;
}

export interface NativeClipboardChangeCountResponse {
  count: number;
}

export interface NativeClipboardFileUrlsResponse {
  value: string;
}

export interface NativeClipboardHasImageResponse {
  has_image: boolean;
}

export interface NativeClipboardHasTextResponse {
  has_text: boolean;
}

export interface NativeClipboardHTMLResponse {
  value: string;
}

export interface NativeClipboardImageDimensionsResponse {
  value: string;
}

export interface NativeClipboardRichTextResponse {
  value: string;
}

export interface NativeClipboardSetHTMLRequest {
  html: string;
}

export interface NativeClipboardSetHTMLResponse {
  ok: boolean;
}

export interface NativeClipboardSetTextRequest {
  text: string;
}

export interface NativeClipboardSetTextResponse {
  ok: boolean;
}

export interface NativeClipboardTypesRequest {
  pasteboard?: string;
}

export interface NativeClipboardTypesResponse {
  types: string[];
}

export interface NativeCloseWindowRequest {
  window_id: string;
}

export interface NativeCloseWindowResponse {
  ok: boolean;
}

export interface NativeColorAtPointRequest {
  x: number;
  y: number;
}

export interface NativeColorAtPointResponse {
  a: number;
  b: number;
  g: number;
  hex: string;
  r: number;
}

export interface NativeComputerNameResponse {
  name: string;
}

export interface NativeContactsPermissionResponse {
  enabled: boolean;
}

export interface NativeCopyFileRequest {
  destination: string;
  source: string;
}

export interface NativeCopyFileResponse {
  ok: boolean;
}

export interface NativeCpuInfoResponse {
  cpu?: unknown;
}

export interface NativeCreateDirectoryRequest {
  path: string;
}

export interface NativeCreateDirectoryResponse {
  ok: boolean;
}

export interface NativeCronJobsResponse {
  jobs: string[];
}

export interface NativeCurrencyCodeResponse {
  code: string;
}

export interface NativeCurrentDatetimeResponse {
  datetime: string;
}

export interface NativeCurrentUserResponse {
  full_name: string;
  home_directory: string;
  username: string;
}

export interface NativeCurrentUserAdminResponse {
  admin: boolean;
}

export interface NativeCurrentWallpaperResponse {
  path: string;
}

export interface NativeCursorResponse {
  x: number;
  y: number;
}

export interface NativeCursorInfoResponse {
  cursor_type: string;
  x: number;
  y: number;
}

export interface NativeCursorShakeToLocateResponse {
  enabled: boolean;
}

export interface NativeDarkModeResponse {
  is_dark: boolean;
}

export interface NativeDateFormatResponse {
  value: string;
}

export interface NativeDefaultAppForUtiRequest {
  uti: string;
}

export interface NativeDefaultAppForUtiResponse {
  bundle_id: string;
}

export interface NativeDefaultBrowserResponse {
  bundle_id: string;
}

export interface NativeDefaultEmailClientResponse {
  bundle_id: string;
}

export interface NativeDefaultPrinterResponse {
  name: string;
}

export interface NativeDeleteFileRequest {
  path: string;
}

export interface NativeDeleteFileResponse {
  ok: boolean;
}

export interface NativeDesktopDirectoryResponse {
  path: string;
}

export interface NativeDetectBarcodesResponse {
  barcodes: BarcodeResult[];
}

export interface NativeDetectBarcodesFileRequest {
  path: string;
}

export interface NativeDetectBarcodesFileResponse {
  barcodes: BarcodeResult[];
}

export interface NativeDictationEnabledResponse {
  enabled: boolean;
}

export interface NativeDifferentiateWithoutColorResponse {
  enabled: boolean;
}

export interface NativeDirectoryContentsRequest {
  include_hidden?: boolean;
  path: string;
}

export interface NativeDirectoryContentsResponse {
  entries: DirectoryEntry[];
}

export interface NativeDiskSpaceRequest {
  path?: string;
}

export interface NativeDiskSpaceResponse {
  available_bytes: number;
  mount_point: string;
  total_bytes: number;
  used_bytes: number;
}

export interface NativeDiskUsageRequest {
  path: string;
}

export interface NativeDiskUsageResponse {
  size: string;
}

export interface NativeDismissNotificationRequest {
  id: string;
}

export interface NativeDismissNotificationResponse {
  ok: boolean;
}

export interface NativeDisplayColorProfilesResponse {
  profiles: DisplayColorProfile[];
}

export interface NativeDisplayCountResponse {
  count: number;
}

export interface NativeDisplayMirroringResponse {
  mirrored: boolean;
}

export interface NativeDisplayRefreshRateRequest {
  display_id: number;
}

export interface NativeDisplayRotationResponse {
  rotations: DisplayRotation[];
}

export interface NativeDisplayScaleFactorRequest {
  display_id: number;
}

export interface NativeDisplaySerialNumberResponse {
  value: string;
}

export interface NativeDisplaysResponse {
  displays: DisplayMetadata[];
}

export interface NativeDndResponse {
  enabled: boolean;
  focus_name?: string;
}

export interface NativeDnsServersResponse {
  servers: string[];
}

export interface NativeDockAutoHideResponse {
  enabled: boolean;
}

export interface NativeDockMagnificationResponse {
  enabled: boolean;
}

export interface NativeDockMinimizeEffectResponse {
  value: string;
}

export interface NativeDockMinimizeToAppResponse {
  enabled: boolean;
}

export interface NativeDockPositionResponse {
  position: string;
}

export interface NativeDockShowIndicatorsResponse {
  enabled: boolean;
}

export interface NativeDockShowRecentsResponse {
  enabled: boolean;
}

export interface NativeDocumentsDirectoryResponse {
  path: string;
}

export interface NativeDownloadsDirectoryResponse {
  path: string;
}

export interface NativeEjectDiskRequest {
  mount_point: string;
}

export interface NativeEjectDiskResponse {
  ok: boolean;
}

export interface NativeEmptyTrashResponse {
  ok: boolean;
}

export interface NativeEnvVarRequest {
  name: string;
}

export interface NativeEnvVarResponse {
  value: string;
}

export interface NativeEpochTimeResponse {
  seconds: number;
}

export interface NativeExtendedAttributesRequest {
  path: string;
}

export interface NativeExternalDisksResponse {
  disks: ExternalDisk[];
}

export interface NativeExternalDisplayNamesResponse {
  names: string[];
}

export interface NativeFanSpeedsResponse {
  value: string;
}

export interface NativeFastUserSwitchingResponse {
  enabled: boolean;
}

export interface NativeFileAclRequest {
  path: string;
}

export interface NativeFileCreationDateRequest {
  path: string;
}

export interface NativeFileExistsRequest {
  path: string;
}

export interface NativeFileExistsResponse {
  exists: boolean;
}

export interface NativeFileExtendedAttributesRequest {
  path: string;
}

export interface NativeFileExtendedAttributesResponse {
  attributes: string[];
}

export interface NativeFileHashRequest {
  algorithm?: string;
  path: string;
}

export interface NativeFileHashResponse {
  hash: string;
}

export interface NativeFileMetadataRequest {
  path: string;
}

export interface NativeFileMetadataResponse {
  accessed?: number;
  created?: number;
  is_dir: boolean;
  is_symlink: boolean;
  modified?: number;
  readonly: boolean;
  size: number;
}

export interface NativeFileModificationDateRequest {
  path: string;
}

export interface NativeFileOwnerRequest {
  path: string;
}

export interface NativeFileOwnerResponse {
  owner: string;
}

export interface NativeFileQuarantineRequest {
  path: string;
}

export interface NativeFileQuarantineResponse {
  quarantined: boolean;
}

export interface NativeFileSharingEnabledResponse {
  enabled: boolean;
}

export interface NativeFileSizeRequest {
  path: string;
}

export interface NativeFileTagsRequest {
  path: string;
  tags?: unknown;
}

export interface NativeFileTypeRequest {
  path: string;
}

export interface NativeFileTypeResponse {
  uti: string;
}

export interface NativeFileUtiRequest {
  path: string;
}

export interface NativeFilevaultStatusResponse {
  enabled: boolean;
}

export interface NativeFinderDefaultViewResponse {
  value: string;
}

export interface NativeFinderNewWindowTargetResponse {
  value: string;
}

export interface NativeFinderSelectionResponse {
  paths: string[];
}

export interface NativeFinderShowExtensionsResponse {
  enabled: boolean;
}

export interface NativeFinderShowHiddenResponse {
  enabled: boolean;
}

export interface NativeFinderShowPathBarResponse {
  enabled: boolean;
}

export interface NativeFinderShowStatusBarResponse {
  enabled: boolean;
}

export interface NativeFinderWindowPathResponse {
  path: string;
}

export interface NativeFirewallEnabledResponse {
  enabled: boolean;
}

export interface NativeFlushDnsResponse {
  ok: boolean;
}

export interface NativeFnKeyFunctionResponse {
  value: string;
}

export interface NativeFocusModesResponse {
  value: string;
}

export interface NativeFocusedElementResponse {
  element?: unknown;
}

export interface NativeFocusedWindowIDResponse {
  window_id: string;
}

export interface NativeFontSmoothingResponse {
  enabled: boolean;
}

export interface NativeForceQuitAppRequest {
  bundle_id: string;
}

export interface NativeForceQuitAppResponse {
  result: boolean;
}

export interface NativeFrontmostAppResponse {
  app?: unknown;
}

export interface NativeFullDiskAccessResponse {
  enabled: boolean;
}

export interface NativeFunctionKeysStandardResponse {
  standard: boolean;
}

export interface NativeGatekeeperStatusResponse {
  enabled: boolean;
}

export interface NativeGatewayAddressResponse {
  address: string;
}

export interface NativeGeneratePdfRequest {
  html: string;
  output_path: string;
}

export interface NativeGeneratePdfResponse {
  ok: boolean;
}

export interface NativeGetWindowInfoRequest {
  window_id: string;
}

export interface NativeGetWindowInfoResponse {
  alpha?: number;
  bounds: WindowBounds;
  display_id: number;
  is_focused: boolean;
  is_fullscreen: boolean;
  is_minimized: boolean;
  subrole?: string;
  title?: string;
  window_id: string;
}

export interface NativeGlobFilesRequest {
  max_results?: number;
  pattern: string;
}

export interface NativeGlobFilesResponse {
  paths: string[];
}

export interface NativeGpuInfoResponse {
  info: string;
}

export interface NativeGrayscaleEnabledResponse {
  enabled: boolean;
}

export interface NativeGroupWindowsByAppResponse {
  enabled: boolean;
}

export interface NativeHandoffEnabledResponse {
  enabled: boolean;
}

export interface NativeHardwareModelResponse {
  model: string;
}

export interface NativeHardwareUuidResponse {
  uuid: string;
}

export interface NativeHidClaimRequest {
  device_id: string;
}

export interface NativeHidClaimResponse {
  success: boolean;
}

export interface NativeHidDevicesResponse {
  devices: HidDeviceEntry[];
}

export interface NativeHidElementsRequest {
  device_id: string;
}

export interface NativeHidElementsResponse {
  elements: HidElementEntry[];
}

export interface NativeHidReleaseRequest {
  device_id: string;
}

export interface NativeHidReleaseResponse {
  success: boolean;
}

export interface NativeHidSendReportRequest {
  data?: number[];
  device_id: string;
  report_id: number;
  report_type: string;
}

export interface NativeHidSendReportResponse {
  success: boolean;
}

export interface NativeHideAppRequest {
  bundle_id: string;
}

export interface NativeHideAppResponse {
  ok: boolean;
}

export interface NativeHighlightColorResponse {
  color: string;
}

export interface NativeHomeDirectoryResponse {
  path: string;
}

export interface NativeHomebrewPrefixResponse {
  prefix: string;
}

export interface NativeHostnameResponse {
  hostname: string;
}

export interface NativeHostnameResolveRequest {
  hostname: string;
}

export interface NativeHostnameResolveResponse {
  addresses: string[];
}

export interface NativeHotCornersResponse {
  corners: string;
}

export interface NativeIcloudDesktopSyncResponse {
  enabled: boolean;
}

export interface NativeIcloudDrivePathResponse {
  path: string;
}

export interface NativeIcloudSignedInResponse {
  signed_in: boolean;
}

export interface NativeIncreaseContrastResponse {
  enabled: boolean;
}

export interface NativeInputSourcesResponse {
  sources: InputSource[];
}

export interface NativeInstalledAppsResponse {
  apps: InstalledApp[];
}

export interface NativeInterfaceStyleSwitcherResponse {
  value: string;
}

export interface NativeIpv6AddressResponse {
  value: string;
}

export interface NativeIsAppHiddenRequest {
  bundle_id: string;
}

export interface NativeIsAppHiddenResponse {
  result: boolean;
}

export interface NativeIsDirectoryRequest {
  path: string;
}

export interface NativeIsDirectoryResponse {
  is_dir: boolean;
}

export interface NativeIsFileHiddenRequest {
  path: string;
}

export interface NativeIsFileHiddenResponse {
  enabled: boolean;
}

export interface NativeKernelVersionResponse {
  version: string;
}

export interface NativeKeyboardLayoutResponse {
  layout_id: string;
  layout_name: string;
  mappings: Record<string, string>;
}

export interface NativeKeychainDeleteRequest {
  account: string;
  service: string;
}

export interface NativeKeychainDeleteResponse {
  ok: boolean;
}

export interface NativeKeychainReadRequest {
  account: string;
  service: string;
}

export interface NativeKeychainReadResponse {
  password: string;
}

export interface NativeKeychainWriteRequest {
  account: string;
  password: string;
  service: string;
}

export interface NativeKeychainWriteResponse {
  ok: boolean;
}

export interface NativeKillProcessRequest {
  pid: number;
  signal?: number;
}

export interface NativeKillProcessResponse {
  ok: boolean;
}

export interface NativeLastRebootResponse {
  date: string;
}

export interface NativeLaunchAppRequest {
  bundle_id: string;
  new_instance?: boolean;
}

export interface NativeLaunchAppResponse {
  ok: boolean;
}

export interface NativeLaunchdAgentsResponse {
  agents: string[];
}

export interface NativeLaunchdDaemonsResponse {
  daemons: string[];
}

export interface NativeListAudioInputDevicesResponse {
  devices: string[];
}

export interface NativeListAudioOutputDevicesResponse {
  devices: string[];
}

export interface NativeListNotificationsResponse {
  notifications: DeliveredNotification[];
}

export interface NativeListShortcutsResponse {
  shortcuts: ShortcutInfo[];
}

export interface NativeListSpacesResponse {
  spaces: SpaceInfo[];
}

export interface NativeLiveTextEnabledResponse {
  enabled: boolean;
}

export interface NativeLocalIPResponse {
  ip: string;
}

export interface NativeLocaleResponse {
  locale: string;
}

export interface NativeLocationEnabledResponse {
  enabled: boolean;
}

export interface NativeLogOutResponse {
  ok: boolean;
}

export interface NativeLoggedInUsersResponse {
  users: string[];
}

export interface NativeLoginItemsResponse {
  items: LoginItem[];
}

export interface NativeLoginItemsModernResponse {
  items: string[];
}

export interface NativeLowPowerModeResponse {
  enabled: boolean;
}

export interface NativeMacAddressResponse {
  value: string;
}

export interface NativeMaximizeWindowRequest {
  window_id: string;
}

export interface NativeMaximizeWindowResponse {
  ok: boolean;
}

export interface NativeMeasurementSystemResponse {
  system: string;
}

export interface NativeMediaNextTrackResponse {
  ok: boolean;
}

export interface NativeMediaPlayPauseResponse {
  ok: boolean;
}

export interface NativeMediaPreviousTrackResponse {
  ok: boolean;
}

export interface NativeMemoryInfoResponse {
  memory?: unknown;
}

export interface NativeMemoryPressureResponse {
  value: string;
}

export interface NativeMenuBarRequest {
  pid: number;
}

export interface NativeMenuBarResponse {
  items: MenuItem[];
}

export interface NativeMenuBarAutoHideResponse {
  enabled: boolean;
}

export interface NativeMenuBarBatteryPercentResponse {
  enabled: boolean;
}

export interface NativeMenuBarClockFormatResponse {
  value: string;
}

export interface NativeMicrophonePermissionResponse {
  enabled: boolean;
}

export interface NativeMinimizeWindowRequest {
  window_id: string;
}

export interface NativeMinimizeWindowResponse {
  ok: boolean;
}

export interface NativeModelNameResponse {
  model: string;
}

export interface NativeMountPointsResponse {
  volumes: string[];
}

export interface NativeMouseButtonClickRequest {
  button: number;
  x?: number;
  y?: number;
}

export interface NativeMouseButtonClickResponse {
  ok: boolean;
}

export interface NativeMoveFileRequest {
  destination: string;
  source: string;
}

export interface NativeMoveFileResponse {
  ok: boolean;
}

export interface NativeMoveWindowToDisplayRequest {
  display_id: number;
  window_id: string;
}

export interface NativeMoveWindowToDisplayResponse {
  ok: boolean;
}

export interface NativeMoveWindowToSpaceRequest {
  space_id: number;
  window_id: string;
}

export interface NativeMoveWindowToSpaceResponse {
  result: boolean;
}

export interface NativeMuteRequest {
  muted: boolean;
}

export interface NativeMuteResponse {
  ok: boolean;
}

export interface NativeNetworkBandwidthResponse {
  value: string;
}

export interface NativeNetworkDnsDomainResponse {
  value: string;
}

export interface NativeNetworkInterfacesResponse {
  interfaces: NetworkInterface[];
}

export interface NativeNetworkProxyEnabledResponse {
  enabled: boolean;
}

export interface NativeNetworkQualityResponse {
  summary: string;
}

export interface NativeNetworkReachableRequest {
  host: string;
}

export interface NativeNetworkReachableResponse {
  reachable: boolean;
}

export interface NativeNetworkSsidResponse {
  value: string;
}

export interface NativeNightShiftResponse {
  enabled: boolean;
}

export interface NativeNotificationSoundEnabledResponse {
  enabled: boolean;
}

export interface NativeNotifyRequest {
  body?: string;
  sound?: string;
  subtitle?: string;
  title: string;
}

export interface NativeNotifyResponse {
  id?: string;
}

export interface NativeNowPlayingResponse {
  info?: unknown;
}

export interface NativeNumberFormatDecimalResponse {
  value: string;
}

export interface NativeObserveWindowsRequest {
  pid: number;
}

export interface NativeObserveWindowsResponse {
  subscription_id: string;
}

export interface NativeOcrClipboardResponse {
  regions: OcrRegion[];
}

export interface NativeOcrFileRequest {
  path: string;
}

export interface NativeOcrFileResponse {
  regions: OcrRegion[];
}

export interface NativeOcrScreenResponse {
  regions: OcrRegion[];
}

export interface NativeOcrScreenRegionRequest {
  height: number;
  width: number;
  x: number;
  y: number;
}

export interface NativeOcrScreenRegionResponse {
  regions: OcrRegion[];
}

export interface NativeOcrWindowRequest {
  window_id: number;
}

export interface NativeOcrWindowResponse {
  regions: OcrRegion[];
}

export interface NativeOpenAppSettingsRequest {
  bundle_id: string;
}

export interface NativeOpenAppSettingsResponse {
  ok: boolean;
}

export interface NativeOpenFinderWindowRequest {
  path: string;
}

export interface NativeOpenFinderWindowResponse {
  ok: boolean;
}

export interface NativeOpenSystemSettingsRequest {
  pane?: string;
}

export interface NativeOpenSystemSettingsResponse {
  ok: boolean;
}

export interface NativeOpenTargetRequest {
  target: string;
}

export interface NativeOpenTargetResponse {
  ok: boolean;
}

export interface NativeOpenURLRequest {
  url: string;
}

export interface NativeOpenURLResponse {
  ok: boolean;
}

export interface NativeOpenWithAppRequest {
  bundle_id: string;
  target: string;
}

export interface NativeOpenWithAppResponse {
  ok: boolean;
}

export interface NativeOptimizedChargingResponse {
  enabled: boolean;
}

export interface NativePdfExtractTextRequest {
  page?: number;
  path: string;
}

export interface NativePdfPageCountRequest {
  path: string;
}

export interface NativePinWindowAboveRequest {
  pinned: boolean;
  window_id: string;
}

export interface NativePinWindowAboveResponse {
  ok: boolean;
}

export interface NativePinchToZoomResponse {
  enabled: boolean;
}

export interface NativePingRequest {
  host: string;
}

export interface NativePlayFeedbackWhenVolumeChangedResponse {
  enabled: boolean;
}

export interface NativePlaySoundRequest {
  name: string;
}

export interface NativePlaySoundResponse {
  ok: boolean;
}

export interface NativePollBurstResponse {
  ok: boolean;
}

export interface NativePowerAdapterConnectedResponse {
  enabled: boolean;
}

export interface NativePowerSourceResponse {
  source: string;
}

export interface NativePressAndHoldEnabledResponse {
  enabled: boolean;
}

export interface NativePreventSleepRequest {
  assertion_id?: string;
  reason?: string;
}

export interface NativePreventSleepResponse {
  assertion_id: string;
}

export interface NativePrimaryDisplayResponse {
  display?: unknown;
}

export interface NativePrimaryDisplayIDResponse {
  value: number;
}

export interface NativePrinterSharingEnabledResponse {
  enabled: boolean;
}

export interface NativePrintersResponse {
  printers: PrinterInfo[];
}

export interface NativeProcessCountResponse {
  count: number;
}

export interface NativeProcessCpuUsageRequest {
  pid: number;
}

export interface NativeProcessExistsRequest {
  pid: number;
}

export interface NativeProcessExistsResponse {
  exists: boolean;
}

export interface NativeProcessInfoRequest {
  pid: number;
}

export interface NativeProcessInfoResponse {
  cpu_percent?: number;
  memory_bytes?: number;
  name: string;
  path?: string;
  pid: number;
  user?: string;
}

export interface NativeProcessListResponse {
  processes: ProcessInfo[];
}

export interface NativeProcessMemoryUsageRequest {
  pid: number;
}

export interface NativeProcessNameRequest {
  pid: number;
}

export interface NativeProcessParentPidRequest {
  pid: number;
}

export interface NativeProcessPathRequest {
  pid: number;
}

export interface NativeProcessStartTimeRequest {
  pid: number;
}

export interface NativeProxySettingsResponse {
  config: string;
}

export interface NativePublicIPResponse {
  ip: string;
}

export interface NativePurgeMemoryResponse {
  ok: boolean;
}

export interface NativeQuickLookRequest {
  path: string;
  size?: number;
}

export interface NativeQuickLookResponse {
  format: string;
  image_base64: string;
}

export interface NativeQuitAppRequest {
  bundle_id: string;
}

export interface NativeQuitAppResponse {
  result: boolean;
}

export interface NativeRaiseWindowRequest {
  window_id: string;
}

export interface NativeRaiseWindowResponse {
  ok: boolean;
}

export interface NativeRandomUuidResponse {
  uuid: string;
}

export interface NativeReadAppPreferenceRequest {
  domain: string;
  key: string;
}

export interface NativeReadFileRequest {
  path: string;
}

export interface NativeReadFileResponse {
  contents: string;
}

export interface NativeReadFileBinaryRequest {
  max_bytes?: number;
  path: string;
}

export interface NativeReadFileBinaryResponse {
  data: string;
}

export interface NativeReadPlistRequest {
  path: string;
}

export interface NativeRecentDocumentsRequest {
  bundle_id: string;
}

export interface NativeRecentDocumentsResponse {
  paths: string[];
}

export interface NativeReduceMotionResponse {
  enabled: boolean;
}

export interface NativeReduceTransparencyResponse {
  enabled: boolean;
}

export interface NativeRemindersIncompleteResponse {
  reminders: ReminderItem[];
}

export interface NativeRemoteLoginEnabledResponse {
  enabled: boolean;
}

export interface NativeRenameFileRequest {
  new_name: string;
  path: string;
}

export interface NativeRenameFileResponse {
  ok: boolean;
}

export interface NativeRequestScreenCaptureResponse {
  prompted: boolean;
}

export interface NativeResourceUsageResponse {
  cpu_usage_percent: number;
  memory_pressure_percent: number;
  memory_total_bytes: number;
  memory_used_bytes: number;
}

export interface NativeRestartAppRequest {
  bundle_id: string;
}

export interface NativeRestartAppResponse {
  ok: boolean;
}

export interface NativeRevealInFinderRequest {
  path: string;
}

export interface NativeRevealInFinderResponse {
  ok: boolean;
}

export interface NativeRosettaInstalledResponse {
  installed: boolean;
}

export interface NativeRunApplescriptRequest {
  script: string;
}

export interface NativeRunApplescriptResponse {
  exit_code: number;
  stderr: string;
  stdout: string;
}

export interface NativeRunJxaRequest {
  script: string;
}

export interface NativeRunJxaResponse {
  output: string;
}

export interface NativeRunShortcutRequest {
  input?: string;
  name: string;
}

export interface NativeRunShortcutResponse {
  output: string;
}

export interface NativeRunningAppsResponse {
  apps: RunningApp[];
}

export interface NativeScreenCapturePermissionResponse {
  granted: boolean;
}

export interface NativeScreenCountResponse {
  count: number;
}

export interface NativeScreenLockResponse {
  ok: boolean;
}

export interface NativeScreenLockedResponse {
  enabled: boolean;
}

export interface NativeScreenResolutionResponse {
  value: string;
}

export interface NativeScreenSaverAskPasswordResponse {
  enabled: boolean;
}

export interface NativeScreenSaverStartResponse {
  ok: boolean;
}

export interface NativeScreenSaverStatusResponse {
  active: boolean;
}

export interface NativeScreenSharingEnabledResponse {
  enabled: boolean;
}

export interface NativeScreenshotRequest {
  display_id?: number;
  region?: unknown;
  window_id?: string;
}

export interface NativeScreenshotResponse {
  format: string;
  image_base64: string;
}

export interface NativeScreenshotFormatResponse {
  value: string;
}

export interface NativeScreenshotIncludeShadowResponse {
  enabled: boolean;
}

export interface NativeScreenshotLocationResponse {
  path: string;
}

export interface NativeScreenshotShowThumbnailResponse {
  enabled: boolean;
}

export interface NativeScrollDirectionResponse {
  natural: boolean;
}

export interface NativeScrollDirectionNaturalResponse {
  enabled: boolean;
}

export interface NativeSearchContactsRequest {
  query: string;
}

export interface NativeSearchContactsResponse {
  contacts: ContactInfo[];
}

export interface NativeSecureInputEnabledResponse {
  enabled: boolean;
}

export interface NativeSelectedFinderItemsResponse {
  paths: string[];
}

export interface NativeSelectedTextResponse {
  text: string;
}

export interface NativeSerialNumberResponse {
  serial: string;
}

export interface NativeSetAirportPowerRequest {
  on: boolean;
}

export interface NativeSetAirportPowerResponse {
  ok: boolean;
}

export interface NativeSetAppHiddenRequest {
  bundle_id: string;
  hidden: boolean;
}

export interface NativeSetAppHiddenResponse {
  ok: boolean;
}

export interface NativeSetAudioDeviceRequest {
  device_type: string;
  uid: string;
}

export interface NativeSetAudioDeviceResponse {
  ok: boolean;
}

export interface NativeSetAudioDeviceVolumeRequest {
  device_uid: string;
  volume: number;
}

export interface NativeSetAudioDeviceVolumeResponse {
  ok: boolean;
}

export interface NativeSetAudioInputDeviceRequest {
  name: string;
}

export interface NativeSetAudioInputDeviceResponse {
  ok: boolean;
}

export interface NativeSetAudioOutputDeviceRequest {
  name: string;
}

export interface NativeSetAudioOutputDeviceResponse {
  ok: boolean;
}

export interface NativeSetAutoRearrangeSpacesRequest {
  enabled: boolean;
}

export interface NativeSetAutoRearrangeSpacesResponse {
  ok: boolean;
}

export interface NativeSetBluetoothPowerRequest {
  on: boolean;
}

export interface NativeSetBluetoothPowerResponse {
  ok: boolean;
}

export interface NativeSetBrightnessRequest {
  brightness: number;
  display_id?: number;
}

export interface NativeSetBrightnessResponse {
  ok: boolean;
}

export interface NativeSetComputerNameRequest {
  name: string;
}

export interface NativeSetComputerNameResponse {
  ok: boolean;
}

export interface NativeSetDarkModeRequest {
  dark: boolean;
}

export interface NativeSetDarkModeResponse {
  ok: boolean;
}

export interface NativeSetDndRequest {
  enabled: boolean;
}

export interface NativeSetDndResponse {
  ok: boolean;
}

export interface NativeSetDockAutoHideRequest {
  enabled: boolean;
}

export interface NativeSetDockAutoHideResponse {
  ok: boolean;
}

export interface NativeSetDockMagnificationRequest {
  enabled: boolean;
}

export interface NativeSetDockMagnificationResponse {
  ok: boolean;
}

export interface NativeSetDockMinimizeEffectRequest {
  effect: string;
}

export interface NativeSetDockMinimizeEffectResponse {
  ok: boolean;
}

export interface NativeSetDockPositionRequest {
  position: string;
}

export interface NativeSetDockPositionResponse {
  ok: boolean;
}

export interface NativeSetDockShowRecentsRequest {
  enabled: boolean;
}

export interface NativeSetDockShowRecentsResponse {
  ok: boolean;
}

export interface NativeSetDockSizeRequest {
  size: number;
}

export interface NativeSetDockSizeResponse {
  ok: boolean;
}

export interface NativeSetExtendedAttributeRequest {
  name: string;
  path: string;
  value: string;
}

export interface NativeSetExtendedAttributeResponse {
  ok: boolean;
}

export interface NativeSetFileHiddenRequest {
  hidden: boolean;
  path: string;
}

export interface NativeSetFileHiddenResponse {
  ok: boolean;
}

export interface NativeSetFilePermissionsRequest {
  mode: string;
  path: string;
}

export interface NativeSetFilePermissionsResponse {
  ok: boolean;
}

export interface NativeSetFinderShowExtensionsRequest {
  enabled: boolean;
}

export interface NativeSetFinderShowExtensionsResponse {
  ok: boolean;
}

export interface NativeSetFinderShowHiddenRequest {
  enabled: boolean;
}

export interface NativeSetFinderShowHiddenResponse {
  ok: boolean;
}

export interface NativeSetHighlightColorRequest {
  color: string;
}

export interface NativeSetHighlightColorResponse {
  ok: boolean;
}

export interface NativeSetHotCornerRequest {
  action: number;
  corner: string;
}

export interface NativeSetHotCornerResponse {
  ok: boolean;
}

export interface NativeSetInputSourceRequest {
  source_id: string;
}

export interface NativeSetInputSourceResponse {
  ok: boolean;
}

export interface NativeSetKeyRepeatDelayRequest {
  delay: number;
}

export interface NativeSetKeyRepeatDelayResponse {
  ok: boolean;
}

export interface NativeSetKeyRepeatRateRequest {
  rate: number;
}

export interface NativeSetKeyRepeatRateResponse {
  ok: boolean;
}

export interface NativeSetMenuBarAutoHideRequest {
  enabled: boolean;
}

export interface NativeSetMenuBarAutoHideResponse {
  ok: boolean;
}

export interface NativeSetMouseSpeedRequest {
  speed: number;
}

export interface NativeSetMouseSpeedResponse {
  ok: boolean;
}

export interface NativeSetNightShiftRequest {
  enabled: boolean;
}

export interface NativeSetNightShiftResponse {
  ok: boolean;
}

export interface NativeSetScreenshotFormatRequest {
  format: string;
}

export interface NativeSetScreenshotFormatResponse {
  ok: boolean;
}

export interface NativeSetScreenshotIncludeShadowRequest {
  enabled: boolean;
}

export interface NativeSetScreenshotIncludeShadowResponse {
  ok: boolean;
}

export interface NativeSetScreenshotLocationRequest {
  path: string;
}

export interface NativeSetScreenshotLocationResponse {
  ok: boolean;
}

export interface NativeSetScrollDirectionNaturalRequest {
  enabled: boolean;
}

export interface NativeSetScrollDirectionNaturalResponse {
  ok: boolean;
}

export interface NativeSetSidebarIconSizeRequest {
  size: number;
}

export interface NativeSetSidebarIconSizeResponse {
  ok: boolean;
}

export interface NativeSetStageManagerRequest {
  enabled: boolean;
}

export interface NativeSetStageManagerResponse {
  ok: boolean;
}

export interface NativeSetTapToClickRequest {
  enabled: boolean;
}

export interface NativeSetTapToClickResponse {
  ok: boolean;
}

export interface NativeSetTrackpadSpeedRequest {
  speed: number;
}

export interface NativeSetTrackpadSpeedResponse {
  ok: boolean;
}

export interface NativeSetURLSchemeHandlerRequest {
  bundle_id: string;
  scheme: string;
}

export interface NativeSetURLSchemeHandlerResponse {
  ok: boolean;
}

export interface NativeSetVolumeRequest {
  volume: number;
}

export interface NativeSetVolumeResponse {
  ok: boolean;
}

export interface NativeSetWallpaperRequest {
  path: string;
}

export interface NativeSetWallpaperResponse {
  ok: boolean;
}

export interface NativeSetWindowAlphaRequest {
  alpha: number;
  window_id: string;
}

export interface NativeSetWindowAlphaResponse {
  ok: boolean;
}

export interface NativeSetWindowLevelRequest {
  level: string;
  window_id: string;
}

export interface NativeSetWindowLevelResponse {
  result: boolean;
}

export interface NativeSetWindowPositionRequest {
  window_id: string;
  x: number;
  y: number;
}

export interface NativeSetWindowPositionResponse {
  ok: boolean;
}

export interface NativeSetWindowShadowRequest {
  enabled: boolean;
  window_id: string;
}

export interface NativeSetWindowShadowResponse {
  ok: boolean;
}

export interface NativeSetWindowSizeRequest {
  h: number;
  w: number;
  window_id: string;
}

export interface NativeSetWindowSizeResponse {
  ok: boolean;
}

export interface NativeSetWindowStickyRequest {
  sticky: boolean;
  window_id: string;
}

export interface NativeSetWindowStickyResponse {
  ok: boolean;
}

export interface NativeSharingNameResponse {
  name: string;
}

export interface NativeShowScrollBarsResponse {
  value: string;
}

export interface NativeSidebarIconSizeResponse {
  value: string;
}

export interface NativeSipStatusResponse {
  enabled: boolean;
}

export interface NativeSiriEnabledResponse {
  enabled: boolean;
}

export interface NativeSleepNowResponse {
  ok: boolean;
}

export interface NativeSlowKeysResponse {
  enabled: boolean;
}

export interface NativeSmartQuotesEnabledResponse {
  enabled: boolean;
}

export interface NativeSmartZoomResponse {
  enabled: boolean;
}

export interface NativeSoundEffectsEnabledResponse {
  enabled: boolean;
}

export interface NativeSpacesSpanDisplaysResponse {
  enabled: boolean;
}

export interface NativeSpeakRequest {
  rate?: number;
  text: string;
  voice?: string;
}

export interface NativeSpeakResponse {
  ok: boolean;
}

export interface NativeSpeechLocalesResponse {
  locales: SpeechLocale[];
}

export interface NativeSpeechRecognitionAvailableResponse {
  available: boolean;
}

export interface NativeSpeechRecognizeFileRequest {
  locale?: string;
  path: string;
}

export interface NativeSpellingLanguageResponse {
  value: string;
}

export interface NativeSpotlightRequest {
  limit?: number;
  query: string;
  scope?: unknown;
}

export interface NativeSpotlightResponse {
  results: SpotlightResult[];
}

export interface NativeStageManagerEnabledResponse {
  enabled: boolean;
}

export interface NativeStartupDiskResponse {
  disk: string;
}

export interface NativeStartupSoundEnabledResponse {
  enabled: boolean;
}

export interface NativeStickyKeysResponse {
  enabled: boolean;
}

export interface NativeSwipeBetweenPagesResponse {
  enabled: boolean;
}

export interface NativeSwitchSpaceRequest {
  space_id: number;
}

export interface NativeSwitchSpaceResponse {
  ok: boolean;
}

export interface NativeSwitchSpaceWhenSwitchingAppResponse {
  enabled: boolean;
}

export interface NativeSymlinkRequest {
  link: string;
  source: string;
}

export interface NativeSymlinkResponse {
  ok: boolean;
}

export interface NativeSystemAppearanceResponse {
  appearance?: unknown;
}

export interface NativeSystemInfoResponse {
  cpu_arch: string;
  model_identifier: string;
  os_build: string;
  os_version: string;
  serial_number?: string;
}

export interface NativeSystemIntegrityInfoResponse {
  value: string;
}

export interface NativeSystemLanguageResponse {
  language: string;
}

export interface NativeSystemRegionResponse {
  region: string;
}

export interface NativeSystemSoundsResponse {
  sounds: string[];
}

export interface NativeSystemUptimeResponse {
  formatted: string;
  uptime_seconds: number;
}

export interface NativeSystemUptimeSecondsResponse {
  seconds: number;
}

export interface NativeTapToClickResponse {
  enabled: boolean;
}

export interface NativeTempDirectoryResponse {
  path: string;
}

export interface NativeTemperatureUnitResponse {
  value: string;
}

export interface NativeTextReplacementsResponse {
  value: string;
}

export interface NativeThermalStateResponse {
  state: string;
}

export interface NativeThreeFingerDragResponse {
  enabled: boolean;
}

export interface NativeThunderboltDevicesResponse {
  value: string;
}

export interface NativeTimeFormatResponse {
  value: string;
}

export interface NativeTimeMachineLastBackupResponse {
  date: string;
}

export interface NativeTimeMachineStatusResponse {
  status: string;
}

export interface NativeTimezoneResponse {
  timezone: string;
}

export interface NativeToggleBluetoothRequest {
  enabled: boolean;
}

export interface NativeToggleBluetoothResponse {
  ok: boolean;
}

export interface NativeToggleFullscreenRequest {
  window_id: string;
}

export interface NativeToggleFullscreenResponse {
  ok: boolean;
}

export interface NativeToggleWifiRequest {
  enabled: boolean;
}

export interface NativeToggleWifiResponse {
  ok: boolean;
}

export interface NativeTouchIDAvailableResponse {
  available: boolean;
}

export interface NativeTransparencyConsentRequest {
  service: string;
}

export interface NativeTrashRequest {
  path: string;
}

export interface NativeTrashResponse {
  result: boolean;
}

export interface NativeTrueToneResponse {
  enabled: boolean;
}

export interface NativeTtsVoicesResponse {
  voices: TtsVoice[];
}

export interface NativeTwentyFourHourClockResponse {
  enabled: boolean;
}

export interface NativeUnhideAppRequest {
  bundle_id: string;
}

export interface NativeUnhideAppResponse {
  ok: boolean;
}

export interface NativeUnminimizeWindowRequest {
  window_id: string;
}

export interface NativeUnminimizeWindowResponse {
  ok: boolean;
}

export interface NativeUnobserveWindowsRequest {
  subscription_id: string;
}

export interface NativeUnobserveWindowsResponse {
  result: boolean;
}

export interface NativeUnzipRequest {
  destination: string;
  source: string;
}

export interface NativeUnzipResponse {
  ok: boolean;
}

export interface NativeURLSchemeHandlerRequest {
  scheme: string;
}

export interface NativeURLSchemeHandlerResponse {
  bundle_id: string;
}

export interface NativeUsbDevicesResponse {
  devices: UsbDevice[];
}

export interface NativeUserAvatarResponse {
  base64_png: string;
}

export interface NativeUserNameResponse {
  name: string;
}

export interface NativeUserShellResponse {
  shell: string;
}

export interface NativeVoiceoverEnabledResponse {
  enabled: boolean;
}

export interface NativeVolumeResponse {
  is_muted: boolean;
  volume: number;
}

export interface NativeVpnStatusResponse {
  active: boolean;
}

export interface NativeWarpCursorRequest {
  x: number;
  y: number;
}

export interface NativeWarpCursorResponse {
  ok: boolean;
}

export interface NativeWifiResponse {
  bssid?: string;
  is_connected: boolean;
  is_enabled: boolean;
  rssi?: number;
  ssid?: string;
}

export interface NativeWifiNetworksResponse {
  networks: string[];
}

export interface NativeWindowAppRequest {
  window_id: string;
}

export interface NativeWindowBoundsRequest {
  window_id: string;
}

export interface NativeWindowBoundsResponse {
  h: number;
  w: number;
  x: number;
  y: number;
}

export interface NativeWindowDisplayIDRequest {
  window_id: string;
}

export interface NativeWindowIsFullscreenRequest {
  window_id: string;
}

export interface NativeWindowIsFullscreenResponse {
  enabled: boolean;
}

export interface NativeWindowIsMinimizedRequest {
  window_id: string;
}

export interface NativeWindowIsMinimizedResponse {
  enabled: boolean;
}

export interface NativeWindowLayerRequest {
  window_id: string;
}

export interface NativeWindowScreenshotRequest {
  window_id: number;
}

export interface NativeWindowSubroleRequest {
  window_id: string;
}

export interface NativeWindowTitleRequest {
  window_id: string;
}

export interface NativeWindowsOnSpaceRequest {
  space_id: number;
}

export interface NativeWindowsOnSpaceResponse {
  window_ids: string[];
}

export interface NativeWorldModelRequest {
  on_screen?: boolean;
}

export interface NativeWriteAppPreferenceRequest {
  domain: string;
  key: string;
  value: unknown;
}

export interface NativeWriteAppPreferenceResponse {
  ok: boolean;
}

export interface NativeWriteFileRequest {
  contents: string;
  path: string;
}

export interface NativeWriteFileResponse {
  ok: boolean;
}

export interface NativeXcodePathResponse {
  path: string;
}

export interface NativeXcodeVersionResponse {
  version: string;
}

export interface NativeZipRequest {
  destination: string;
  source: string;
}

export interface NativeZipResponse {
  ok: boolean;
}

export interface NativeZoomEnabledResponse {
  enabled: boolean;
}

export interface OverridesApplyRequest {
  action: string;
  collection: string;
  fields?: unknown;
  id?: string;
  new_id?: string;
}

export interface OverridesApplyResponse {
  key?: string;
  ok: boolean;
}

export interface PipelinesGrammarRequest {
  full?: boolean;
}

export interface PipelinesGrammarResponse {
  vocabulary_update?: unknown;
  words: string[];
}

export interface PipelinesInjectRequest {
  data?: unknown;
  event_type: string;
  name: string;
}

export interface PipelinesInjectResponse {
  injected: boolean;
}

export interface PipelinesRunRequest {
  ephemeral?: boolean;
  name: string;
  param_overrides?: Record<string, unknown>;
}

export interface PipelinesRunResponse {
  reason?: string;
  started: boolean;
}

export interface PipelinesStatusResponse {
  pipelines: PipelineStatusEntry[];
  pool_stages: PoolStageStatusEntry[];
  running: string[];
}

export interface PipelinesStopRequest {
  name: string;
}

export interface PipelinesStopResponse {
  stopped: boolean;
}

export interface PipelinesWarmRequest {
  name: string;
}

export interface PipelinesWarmResponse {
  warmed: boolean;
}

export interface PluginDebugRequest {
  data?: unknown;
  level?: unknown;
  tag?: string;
}

export interface PluginDebugResponse {
  ok: boolean;
}

export interface PrivacyGetRecordingRequest {
  name: string;
}

export interface PrivacyGetRecordingResponse {
  enabled: boolean;
}

export interface PrivacySetRecordingRequest {
  enabled: boolean;
  name: string;
}

export interface PrivacySetRecordingResponse {
  ok: boolean;
}

export interface SelectionPickRequest {
  index: number;
}

export interface SelectionPickResponse {
  control_message: string;
  item_id: string;
  ok: boolean;
  reset_engine: boolean;
}

export interface SelectionSetRequest {
  channel?: string;
  items?: unknown;
  title?: string;
}

export interface SelectionSetResponse {
  ok: boolean;
}

export interface SessionBoundaryResponse {
  ok: boolean;
}

export interface SessionEndCleanupResponse {
  control_message?: string;
  ok: boolean;
  reset_engine: boolean;
}

export interface SettingsPatchSignalsRequest {
  signals: string;
}

export interface SettingsPatchSignalsResponse {
  ok: boolean;
}

export interface SettingsRedirectRequest {
  tab: string;
}

export interface SettingsRedirectResponse {
  ok: boolean;
}

export interface SettingsRefreshResponse {
  ok: boolean;
}

export interface SettingsRulesCreateRequest {
  newruleactionjson?: string;
  newruleactiontype?: string;
  newruleactionval?: string;
  newrulecategory?: string;
  newruleclearstags?: string;
  newruledescription?: string;
  newrulephrase?: string;
  newrulerequirestags?: string;
  newrulesetstags?: string;
}

export interface SettingsRulesCreateResponse {
  conflict?: string;
  ok: boolean;
}

export interface SettingsRulesUpdateRequest {
  canonical: string;
  newruleactionjson?: string;
  newruleactiontype?: string;
  newruleactionval?: string;
  newrulecategory?: string;
  newruleclearstags?: string;
  newruledescription?: string;
  newrulephrase?: string;
  newrulerequirestags?: string;
  newrulesetstags?: string;
}

export interface SettingsRulesUpdateResponse {
  conflict?: string;
  ok: boolean;
}

export interface SystemLaunchAppRequest {
  bundle_id: string;
  new_instance?: boolean;
}

export interface SystemLaunchAppResponse {
  ok: boolean;
}

export interface SystemNotifyRequest {
  body: string;
  duration_secs?: number;
  title: string;
}

export interface SystemNotifyResponse {
  ok: boolean;
}

export interface SystemRunShellRequest {
  command: string;
}

export interface SystemRunShellResponse {
  ok: boolean;
}

export interface VocabularyCommitResponse {
  ok: boolean;
}

// ===== Actuator → Plugin request/response types =====

export interface CalibrationApplyFixtureRequest {
  command_id: string;
}

export interface CalibrationApplyFixtureResponse {
  fixture_handle: string;
}

export interface CalibrationReleaseFixtureRequest {
  fixture_handle: string;
}

export interface CalibrationSamplesRequest {
  command_id: string;
}

export interface CalibrationSamplesResponse {
  prompts: string[];
}

export interface OnActionRequest {
  action: string;
  active_app?: string;
  active_window_id?: string;
  params?: unknown;
  phase?: string;
}

export interface OnActionResponse {
  control_message?: string;
  result?: unknown;
  status: OnActionStatus;
}

export interface OnCommandsChangedRequest {
  commands_by_plugin: unknown;
  user_commands?: unknown[];
}

export interface OnCommandsChangedResponse {
  processed_count: number;
}

export interface RenderHUDRequest {
  footer?: string;
  hud_mode: string;
  sections?: HudSection[];
  title?: string;
}

export interface RenderSettingsRequest {
  action_type_schemas?: Record<string, ActionTypeSchema>;
  collection_data?: Record<string, unknown>;
  command_filter?: string;
  commands?: CommandRowData[];
  list_schemas?: Record<string, SettingsListSchemaInfo>;
  search: string;
  tab_key: string;
  tag_schemas?: Record<string, SettingsTagSchemaInfo>;
}

export interface RenderSettingsResponse {
  css?: string;
  html: string;
}
